<?php
/*
clase EPC INNOVA
CREADO : 10/mayo/2023
TESTER: FATIMA ARELLANO
PROGRAMER: SANDOR ACTUALIZACION: 1 MAY 2023

*/
	define('__ROOT3__', dirname(dirname(__FILE__)));
	require __ROOT3__."/includes/class.epcinn.php";
	//$conexion = NEW accesoclase();
	class accesoclase extends ambientetrabajo{




/**//**//**//**//*carga empresa corporativo*//**//**//**//**/




	public function variables_empresascorporativo(){
		$conn = $this->db();
		$variablequery = "select * from 03datosdelaempresa where idRelacion = '".$_SESSION['id']."' ";
		$arrayquery = mysqli_query($conn,$variablequery);
		return $row = mysqli_fetch_array($arrayquery, MYSQLI_ASSOC);		
	}




	public function revisar_empresascorporativo(){
		$conn = $this->db();
		$var1 = 'select id from 03datosdelaempresa  where idRelacion =  "'.$_SESSION['id'].'" ';
		$query = mysqli_query($conn,$var1) or die('P44'.mysqli_error($conn));
		$row = mysqli_fetch_array($query, MYSQLI_ASSOC);
		return $row['id'];
	}

	public function guardarCorp ( $NFE_INFORMACION , $NFE_OBSERVACIONES , $NFE_FECHA_ULTIMACARGA , $NCE_INFORMACION , 
	$NCE_OBSERVACIONES , $NCE_FECHA_ULTIMA_CARGA , $RFC_INFORMACION , $RFC_OBSERVACIONES , $RFC_FECHA_ULTIMA_CARGA , 
	$GDE_INFORMACION , $GDE_OBSERVACIONES , $GDE_FECHA_ULTIMA_CARGA , $hDatosCorp , $DCORP_ENVIAR_IMAIL , $CP_MONTO_PAGADO , 
	$CP_CONCEPTO , $P_UBICACION_MAPA_EPC ){
		
		
		$conn = $this->db();
		$existe = $this->revisar_empresascorporativo();
		$session = isset($_SESSION['id'])?$_SESSION['id']:'';
		if($session != ''){
			
			
		$var1 = "update 03datosdelaempresa set NFE_INFORMACION = '".$NFE_INFORMACION."' , NFE_OBSERVACIONES = '".$NFE_OBSERVACIONES."' , NFE_FECHA_ULTIMACARGA = '".$NFE_FECHA_ULTIMACARGA."' , NCE_INFORMACION = '".$NCE_INFORMACION."' , NCE_OBSERVACIONES = '".$NCE_OBSERVACIONES."' , NCE_FECHA_ULTIMA_CARGA = '".$NCE_FECHA_ULTIMA_CARGA."' , RFC_INFORMACION = '".$RFC_INFORMACION."' , RFC_OBSERVACIONES = '".$RFC_OBSERVACIONES."' , RFC_FECHA_ULTIMA_CARGA = '".$RFC_FECHA_ULTIMA_CARGA."' , GDE_INFORMACION = '".$GDE_INFORMACION."' , GDE_OBSERVACIONES = '".$GDE_OBSERVACIONES."' , GDE_FECHA_ULTIMA_CARGA = '".$GDE_FECHA_ULTIMA_CARGA."' , hDatosCorp = '".$hDatosCorp."' , DCORP_ENVIAR_IMAIL = '".$DCORP_ENVIAR_IMAIL."' where idRelacion = '".$session."' ;  ";

		
		$var2 = "insert into 03datosdelaempresa (
		NFE_INFORMACION, NFE_OBSERVACIONES, NFE_FECHA_ULTIMACARGA, NCE_INFORMACION, 
		NCE_OBSERVACIONES, NCE_FECHA_ULTIMA_CARGA, RFC_INFORMACION, RFC_OBSERVACIONES, 
		RFC_FECHA_ULTIMA_CARGA, GDE_INFORMACION, GDE_OBSERVACIONES, GDE_FECHA_ULTIMA_CARGA,
		hDatosCorp, DCORP_ENVIAR_IMAIL, idRelacion) values ( 
		'".$NFE_INFORMACION."' , '".$NFE_OBSERVACIONES."' , '".$NFE_FECHA_ULTIMACARGA."' , '".$NCE_INFORMACION."' , 
		'".$NCE_OBSERVACIONES."' , '".$NCE_FECHA_ULTIMA_CARGA."' , '".$RFC_INFORMACION."' , '".$RFC_OBSERVACIONES."' , 
		'".$RFC_FECHA_ULTIMA_CARGA."' , '".$GDE_INFORMACION."' , '".$GDE_OBSERVACIONES."' , '".$GDE_FECHA_ULTIMA_CARGA."' ,
		'".$hDatosCorp."' , '".$DCORP_ENVIAR_IMAIL."' , '".$session."' );  ";
		
		
			
		if($ICONVENIOPAGO22 == 'ICONVENIOPAGO22'){

		mysqli_query($conn,$var1) or die('P276'.mysqli_error($conn));
		return "Actualizado";
		}else{
		mysqli_query($conn,$var2) or die('P279'.mysqli_error($conn));
		return "Ingresado";
		}
		}else{
		echo "NO HAY UN USUARIO SELECCIONADO";	
		}	
	}









/**//**//**//**//*carga datoa fiscales de la empresas del  corporativo*//**//**//**//**/




	public function variables_empresascorporativo(){
		$conn = $this->db();
		$variablequery = "select * from 03datosfiscalesempresa where idRelacion = '".$_SESSION['id']."' ";
		$arrayquery = mysqli_query($conn,$variablequery);
		return $row = mysqli_fetch_array($arrayquery, MYSQLI_ASSOC);		
	}




	public function revisar_empresascorporativo(){
		$conn = $this->db();
		$var1 = 'select id from 03datosfiscalesempresa  where idRelacion =  "'.$_SESSION['id'].'" ';
		$query = mysqli_query($conn,$var1) or die('P44'.mysqli_error($conn));
		$row = mysqli_fetch_array($query, MYSQLI_ASSOC);
		return $row['id'];
	}

	public function guardarDATOSCORPFISCAL ($ED_INFORMACION , $ED_OBSERVACIONES , $ED_FECHA_ULTIMA_CARGA , $CA_INFORMACION , $CA_OBSERVACIONES , $CA_FECHA_ULTIMA_CARGA , $NE_INFORMACION , $NE_OBSERVACIONES , $NE_FECHA_ULTIMA_CARGA , $NI_INFORMACION , $NI_OBSERVACIONES , $NI_FECHA_ULTIMA_CARGA , $NDO_INFORMACION , $NDO_OBSERVACIONES , $NDO_FECHA_ULTIMA_CARGA , $COL_INFORMACION , $COL_OBSERVACIONES , $COL_FECHA_ULTIMA_CARGA , $AL_INFORMACION , $AL_OBSERVACIONES , $AL_FECHA_ULTIMA_CARGA , $CP_INFORMACION , $CP_OBSERVACIONES , $CP_FECHA_ULTIMA_CARGA , $CIU_INFORMACION , $CIU_OBSERVACIONES , $CIU_FECHA_ULTIMA_CARGA , $ES_INFORMACION , $ES_OBSERVACIONES , $ES_FECHA_ULTIMA_CARGA , $PA_INFORMACION , $PA_OBSERVACIONES , $PA_FECHA_ULTIMA_CARGA , $P_UBICACION_MAPA_EPC , $O_UBICACION_MAPA_EPC , $F_UBICACION_MAPA_EPC , $TEL_INFORMACION , $TEL_OBSERVACIONES , $TEL_FECHA_ULTIMA_CARGA , $TEL2_INFORMACION , $TEL2_OBSERVACIONES , $TEL2_FECHA_ULTIMA_CARGA , $WHA_INFORMACION , $WHA_OBSERVACIONES , $WHA_FECHA_ULTIMA_CARGA , $PAG_INFORMACION , $PAG_OBSERVACIONES , $PAG_FECHA_ULTIMA_CARGA , $NAP_INFORMACION , $NAP_OBSERVACIONES , $NAP_FECHA_ULTIMA_CARGA , $hDatosCorpfiscal , $DCORPF_ENVIAR_IMAIL ){
		
		
		$conn = $this->db();
		$existe = $this->revisar_empresascorporativo();
		$session = isset($_SESSION['id'])?$_SESSION['id']:'';
		if($session != ''){
			
			
		$var1 =  "update 03datosfiscalesempresa set ED_INFORMACION = '".$ED_INFORMACION."' , ED_OBSERVACIONES = '".$ED_OBSERVACIONES."' , ED_FECHA_ULTIMA_CARGA = '".$ED_FECHA_ULTIMA_CARGA."' , CA_INFORMACION = '".$CA_INFORMACION."' , CA_OBSERVACIONES = '".$CA_OBSERVACIONES."' , CA_FECHA_ULTIMA_CARGA = '".$CA_FECHA_ULTIMA_CARGA."' , NE_INFORMACION = '".$NE_INFORMACION."' , NE_OBSERVACIONES = '".$NE_OBSERVACIONES."' , NE_FECHA_ULTIMA_CARGA = '".$NE_FECHA_ULTIMA_CARGA."' , NI_INFORMACION = '".$NI_INFORMACION."' , NI_OBSERVACIONES = '".$NI_OBSERVACIONES."' , NI_FECHA_ULTIMA_CARGA = '".$NI_FECHA_ULTIMA_CARGA."' , NDO_INFORMACION = '".$NDO_INFORMACION."' , NDO_OBSERVACIONES = '".$NDO_OBSERVACIONES."' , NDO_FECHA_ULTIMA_CARGA = '".$NDO_FECHA_ULTIMA_CARGA."' , COL_INFORMACION = '".$COL_INFORMACION."' , COL_OBSERVACIONES = '".$COL_OBSERVACIONES."' , COL_FECHA_ULTIMA_CARGA = '".$COL_FECHA_ULTIMA_CARGA."' , AL_INFORMACION = '".$AL_INFORMACION."' , AL_OBSERVACIONES = '".$AL_OBSERVACIONES."' , AL_FECHA_ULTIMA_CARGA = '".$AL_FECHA_ULTIMA_CARGA."' , CP_INFORMACION = '".$CP_INFORMACION."' , CP_OBSERVACIONES = '".$CP_OBSERVACIONES."' , CP_FECHA_ULTIMA_CARGA = '".$CP_FECHA_ULTIMA_CARGA."' , CIU_INFORMACION = '".$CIU_INFORMACION."' , CIU_OBSERVACIONES = '".$CIU_OBSERVACIONES."' , CIU_FECHA_ULTIMA_CARGA = '".$CIU_FECHA_ULTIMA_CARGA."' , ES_INFORMACION = '".$ES_INFORMACION."' , ES_OBSERVACIONES = '".$ES_OBSERVACIONES."' , ES_FECHA_ULTIMA_CARGA = '".$ES_FECHA_ULTIMA_CARGA."' , PA_INFORMACION = '".$PA_INFORMACION."' , PA_OBSERVACIONES = '".$PA_OBSERVACIONES."' , PA_FECHA_ULTIMA_CARGA = '".$PA_FECHA_ULTIMA_CARGA."' , P_UBICACION_MAPA_EPC = '".$P_UBICACION_MAPA_EPC."' , O_UBICACION_MAPA_EPC = '".$O_UBICACION_MAPA_EPC."' , F_UBICACION_MAPA_EPC = '".$F_UBICACION_MAPA_EPC."' , TEL_INFORMACION = '".$TEL_INFORMACION."' , TEL_OBSERVACIONES = '".$TEL_OBSERVACIONES."' , TEL_FECHA_ULTIMA_CARGA = '".$TEL_FECHA_ULTIMA_CARGA."' , TEL2_INFORMACION = '".$TEL2_INFORMACION."' , TEL2_OBSERVACIONES = '".$TEL2_OBSERVACIONES."' , TEL2_FECHA_ULTIMA_CARGA = '".$TEL2_FECHA_ULTIMA_CARGA."' , WHA_INFORMACION = '".$WHA_INFORMACION."' , WHA_OBSERVACIONES = '".$WHA_OBSERVACIONES."' , WHA_FECHA_ULTIMA_CARGA = '".$WHA_FECHA_ULTIMA_CARGA."' , PAG_INFORMACION = '".$PAG_INFORMACION."' , PAG_OBSERVACIONES = '".$PAG_OBSERVACIONES."' , PAG_FECHA_ULTIMA_CARGA = '".$PAG_FECHA_ULTIMA_CARGA."' , NAP_INFORMACION = '".$NAP_INFORMACION."' , NAP_OBSERVACIONES = '".$NAP_OBSERVACIONES."' , NAP_FECHA_ULTIMA_CARGA = '".$NAP_FECHA_ULTIMA_CARGA."' , hDatosCorpfiscal = '".$hDatosCorpfiscal."' , DCORPF_ENVIAR_IMAIL = '".$DCORPF_ENVIAR_IMAIL."' , where idRelacion = '".$session."' ; 
		
		
		
		
		$var2 = insert into 03datosfiscalesempresa ( ED_INFORMACION, ED_OBSERVACIONES, ED_FECHA_ULTIMA_CARGA, CA_INFORMACION, CA_OBSERVACIONES, CA_FECHA_ULTIMA_CARGA, NE_INFORMACION, NE_OBSERVACIONES, NE_FECHA_ULTIMA_CARGA, NI_INFORMACION, NI_OBSERVACIONES, NI_FECHA_ULTIMA_CARGA, NDO_INFORMACION, NDO_OBSERVACIONES, NDO_FECHA_ULTIMA_CARGA, COL_INFORMACION, COL_OBSERVACIONES, COL_FECHA_ULTIMA_CARGA, AL_INFORMACION, AL_OBSERVACIONES, AL_FECHA_ULTIMA_CARGA, CP_INFORMACION, CP_OBSERVACIONES, CP_FECHA_ULTIMA_CARGA, CIU_INFORMACION, CIU_OBSERVACIONES, CIU_FECHA_ULTIMA_CARGA, ES_INFORMACION, ES_OBSERVACIONES, ES_FECHA_ULTIMA_CARGA, PA_INFORMACION, PA_OBSERVACIONES, PA_FECHA_ULTIMA_CARGA, P_UBICACION_MAPA_EPC, O_UBICACION_MAPA_EPC, F_UBICACION_MAPA_EPC, TEL_INFORMACION, TEL_OBSERVACIONES, TEL_FECHA_ULTIMA_CARGA, TEL2_INFORMACION, TEL2_OBSERVACIONES, TEL2_FECHA_ULTIMA_CARGA, WHA_INFORMACION, WHA_OBSERVACIONES, WHA_FECHA_ULTIMA_CARGA, PAG_INFORMACION, PAG_OBSERVACIONES, PAG_FECHA_ULTIMA_CARGA, NAP_INFORMACION, NAP_OBSERVACIONES, NAP_FECHA_ULTIMA_CARGA, hDatosCorpfiscal, DCORPF_ENVIAR_IMAIL, idRelacion) values ( '".$ED_INFORMACION."' , '".$ED_OBSERVACIONES."' , '".$ED_FECHA_ULTIMA_CARGA."' , '".$CA_INFORMACION."' , '".$CA_OBSERVACIONES."' , '".$CA_FECHA_ULTIMA_CARGA."' , '".$NE_INFORMACION."' , '".$NE_OBSERVACIONES."' , '".$NE_FECHA_ULTIMA_CARGA."' , '".$NI_INFORMACION."' , '".$NI_OBSERVACIONES."' , '".$NI_FECHA_ULTIMA_CARGA."' , '".$NDO_INFORMACION."' , '".$NDO_OBSERVACIONES."' , '".$NDO_FECHA_ULTIMA_CARGA."' , '".$COL_INFORMACION."' , '".$COL_OBSERVACIONES."' , '".$COL_FECHA_ULTIMA_CARGA."' , '".$AL_INFORMACION."' , '".$AL_OBSERVACIONES."' , '".$AL_FECHA_ULTIMA_CARGA."' , '".$CP_INFORMACION."' , '".$CP_OBSERVACIONES."' , '".$CP_FECHA_ULTIMA_CARGA."' , '".$CIU_INFORMACION."' , '".$CIU_OBSERVACIONES."' , '".$CIU_FECHA_ULTIMA_CARGA."' , '".$ES_INFORMACION."' , '".$ES_OBSERVACIONES."' , '".$ES_FECHA_ULTIMA_CARGA."' , '".$PA_INFORMACION."' , '".$PA_OBSERVACIONES."' , '".$PA_FECHA_ULTIMA_CARGA."' , '".$P_UBICACION_MAPA_EPC."' , '".$O_UBICACION_MAPA_EPC."' , '".$F_UBICACION_MAPA_EPC."' , '".$TEL_INFORMACION."' , '".$TEL_OBSERVACIONES."' , '".$TEL_FECHA_ULTIMA_CARGA."' , '".$TEL2_INFORMACION."' , '".$TEL2_OBSERVACIONES."' , '".$TEL2_FECHA_ULTIMA_CARGA."' , '".$WHA_INFORMACION."' , '".$WHA_OBSERVACIONES."' , '".$WHA_FECHA_ULTIMA_CARGA."' , '".$PAG_INFORMACION."' , '".$PAG_OBSERVACIONES."' , '".$PAG_FECHA_ULTIMA_CARGA."' , '".$NAP_INFORMACION."' , '".$NAP_OBSERVACIONES."' , '".$NAP_FECHA_ULTIMA_CARGA."' , '".$hDatosCorpfiscal."' , '".$DCORPF_ENVIAR_IMAIL."' , '".$session."' ); 
		
		
			
		if($ICONVENIOPAGO22 == 'ICONVENIOPAGO22'){

		mysqli_query($conn,$var1) or die('P276'.mysqli_error($conn));
		return "Actualizado";
		}else{
		mysqli_query($conn,$var2) or die('P279'.mysqli_error($conn));
		return "Ingresado";
		}
		}else{
		echo "NO HAY UN USUARIO SELECCIONADO";	
		}	
	}
	
	
	}





?>