<?php
    if(!isset($_SESSION)) 
    { 
        session_start(); 
    }

define('__ROOT1__', dirname(dirname(__FILE__)));
include_once (__ROOT1__."/includes/error_reporting.php");
include_once (__ROOT1__."/includes/class.epcinn.php");

$conexion = NEW colaboradores();
$listado = isset($_POST["listado"])?$_POST["listado"]:"";
$empresa = isset($_POST["empresa"])?$_POST["empresa"]:""; 
$ipersonal1 = isset($_POST["ipersonal1"])?$_POST["ipersonal1"]:"";
$dircasa11 = isset($_POST["dircasa11"])?$_POST["dircasa11"]:"";
$dircasa22 = isset($_POST["dircasa22"])?$_POST["dircasa22"]:"";
$F1CERCANO1 = isset($_POST["F1CERCANO1"])?$_POST["F1CERCANO1"]:"";
$F2CERCANO2 = isset($_POST["F2CERCANO2"])?$_POST["F2CERCANO2"]:"";
$F3CERCANO3 = isset($_POST["F3CERCANO3"])?$_POST["F3CERCANO3"]:"";
$F4CERCANO4 = isset($_POST["F4CERCANO4"])?$_POST["F4CERCANO4"]:"";
$habilidades1 = isset($_POST["habilidades1"])?$_POST["habilidades1"]:"";

if($listado == 'listado' ){
	
$USUARIO_CRM = isset($_POST["USUARIO_CRM"])?$_POST["USUARIO_CRM"]:"";
$CONTRASENIA_CRM = isset($_POST["CONTRASENIA_CRM"])?$_POST["CONTRASENIA_CRM"]:"";
$NIVEL_ACCESO = isset($_POST["NIVEL_ACCESO"])?$_POST["NIVEL_ACCESO"]:"";
$PUESTO = isset($_POST["PUESTO"])?$_POST["PUESTO"]:"";
$DEPARTAMENTO = isset($_POST["DEPARTAMENTO"])?$_POST["DEPARTAMENTO"]:"";
$CORREO_1 = isset($_POST["CORREO_1"])?$_POST["CORREO_1"]:"";
$NOMBRE_1 = isset($_POST["NOMBRE_1"])?$_POST["NOMBRE_1"]:"";
$APELLIDO_PATERNO = isset($_POST["APELLIDO_PATERNO"])?$_POST["APELLIDO_PATERNO"]:"";
$APELLIDO_MATERNO = isset($_POST["APELLIDO_MATERNO"])?$_POST["APELLIDO_MATERNO"]:"";
$STATUS_CARGA_INFORMACION = isset($_POST["STATUS_CARGA_INFORMACION"])?$_POST["STATUS_CARGA_INFORMACION"]:"";
if($USUARIO_CRM =='' OR $CONTRASENIA_CRM=='' OR  $NIVEL_ACCESO=='' OR  $PUESTO=='' OR  $DEPARTAMENTO=='' OR  $CORREO_1=='' OR $NOMBRE_1=='' OR  $APELLIDO_PATERNO=='' OR  $APELLIDO_MATERNO=='' OR  $STATUS_CARGA_INFORMACION=='' ){
	echo "<P style='color:red; font-size:15px;'>LLENAR TODOS LOS CAMPOS</p>";
}else{

//require"crea_funciones.php";

echo $conexion->guardar_listado($USUARIO_CRM , $CONTRASENIA_CRM , $NIVEL_ACCESO , $PUESTO , $DEPARTAMENTO , $CORREO_1 , $NOMBRE_1 , $APELLIDO_PATERNO , $APELLIDO_MATERNO , $listado , $STATUS_CARGA_INFORMACION  );
	
}

}
elseif($empresa == 'empresa'){
	
$FECHA_INGRESO = isset($_POST["FECHA_INGRESO"])?$_POST["FECHA_INGRESO"]:"";
$NUMERO_COLABORADOR = isset($_POST["NUMERO_COLABORADOR"])?$_POST["NUMERO_COLABORADOR"]:"";
$NUMERO_REGISTRO_BIOMETRICO = isset($_POST["NUMERO_REGISTRO_BIOMETRICO"])?$_POST["NUMERO_REGISTRO_BIOMETRICO"]:"";
$CONTRASENIA_REGISTRO_BIOMETRICO = isset($_POST["CONTRASENIA_REGISTRO_BIOMETRICO"])?$_POST["CONTRASENIA_REGISTRO_BIOMETRICO"]:"";
$USUARIO_CRM = isset($_POST["USUARIO_CRM"])?$_POST["USUARIO_CRM"]:"";
$CONTRASENIA_CRM = isset($_POST["CONTRASENIA_CRM"])?$_POST["CONTRASENIA_CRM"]:"";
$NIVEL_ACCESO_CRM = isset($_POST["NIVEL_ACCESO_CRM"])?$_POST["NIVEL_ACCESO_CRM"]:"";
$PUESTO = isset($_POST["PUESTO"])?$_POST["PUESTO"]:"";
$DEPARTAMENTO = isset($_POST["DEPARTAMENTO"])?$_POST["DEPARTAMENTO"]:"";
$NUMERO_TARJETA_CREDITO = isset($_POST["NUMERO_TARJETA_CREDITO"])?$_POST["NUMERO_TARJETA_CREDITO"]:"";
$CORREO_1 = isset($_POST["CORREO_1"])?$_POST["CORREO_1"]:"";
$CORREO_2 = isset($_POST["CORREO_2"])?$_POST["CORREO_2"]:"";
$CORREO_3 = isset($_POST["CORREO_3"])?$_POST["CORREO_3"]:"";
$FECHA_SALIDA_EMPRESA = isset($_POST["FECHA_SALIDA_EMPRESA"])?$_POST["FECHA_SALIDA_EMPRESA"]:"";
$MOTIVO_SALIDA_EMPRESA = isset($_POST["MOTIVO_SALIDA_EMPRESA"])?$_POST["MOTIVO_SALIDA_EMPRESA"]:""; 

if($FECHA_INGRESO  =='' OR  $NUMERO_COLABORADOR  =='' OR  $NUMERO_REGISTRO_BIOMETRICO  =='' OR  $CONTRASENIA_REGISTRO_BIOMETRICO  =='' OR  $USUARIO_CRM  =='' OR  $CONTRASENIA_CRM  =='' OR  $NIVEL_ACCESO_CRM  =='' OR  $PUESTO  =='' OR  $DEPARTAMENTO  =='' OR  $NUMERO_TARJETA_CREDITO  =='' OR  $CORREO_1  =='' OR  $CORREO_2  =='' OR  $CORREO_3  =='' OR  $FECHA_SALIDA_EMPRESA  =='' OR  $MOTIVO_SALIDA_EMPRESA  =='' OR  $empresa =='' ){
	echo "<P style='color:red; font-size:15px;'>LLENAR TODOS LOS CAMPOS</p>";
}else{


//include_once (__ROOT1__."/includes/crea_funciones.php");
echo $conexion->guardar_empresa( $FECHA_INGRESO , $NUMERO_COLABORADOR , $NUMERO_REGISTRO_BIOMETRICO , $CONTRASENIA_REGISTRO_BIOMETRICO , $USUARIO_CRM , $CONTRASENIA_CRM , $NIVEL_ACCESO_CRM , $PUESTO , $DEPARTAMENTO , $NUMERO_TARJETA_CREDITO , $CORREO_1 , $CORREO_2 , $CORREO_3 , $FECHA_SALIDA_EMPRESA , $MOTIVO_SALIDA_EMPRESA);
	
}

}
elseif($ipersonal1 == 'ipersonal1'){

$NOMBRE_1 = isset($_POST["NOMBRE_1"])?$_POST["NOMBRE_1"]:"";
$NOMBRE_2 = isset($_POST["NOMBRE_2"])?$_POST["NOMBRE_2"]:"";
$NOMBRE_3 = isset($_POST["NOMBRE_3"])?$_POST["NOMBRE_3"]:"";
$APELLIDO_MATERNO = isset($_POST["APELLIDO_MATERNO"])?$_POST["APELLIDO_MATERNO"]:"";
$APELLIDO_PATERNO = isset($_POST["APELLIDO_PATERNO"])?$_POST["APELLIDO_PATERNO"]:"";

$IPCORREO1 = isset($_POST["IPCORREO1"])?$_POST["IPCORREO1"]:"";
$IPCORREO2 = isset($_POST["IPCORREO2"])?$_POST["IPCORREO2"]:"";

$FECHA_DE_NACIMIENTO = isset($_POST["FECHA_DE_NACIMIENTO"])?$_POST["FECHA_DE_NACIMIENTO"]:"";
$ANIOS = isset($_POST["ANIOS"])?$_POST["ANIOS"]:"";
$LUGAR_DE_NACIMIENTO_ESTADO_PROVINCIA = isset($_POST["LUGAR_DE_NACIMIENTO_ESTADO_PROVINCIA"])?$_POST["LUGAR_DE_NACIMIENTO_ESTADO_PROVINCIA"]:"";
$PAIS_DE_NACIMIENTO = isset($_POST["PAIS_DE_NACIMIENTO"])?$_POST["PAIS_DE_NACIMIENTO"]:"";
$ESTADO_CIVIL = isset($_POST["ESTADO_CIVIL"])?$_POST["ESTADO_CIVIL"]:"";
$NUMERO_DE_FAMILIARES_PADRES_HERMANOS = isset($_POST["NUMERO_DE_FAMILIARES_PADRES_HERMANOS"])?$_POST["NUMERO_DE_FAMILIARES_PADRES_HERMANOS"]:"";
$NUMERO_DE_FAMILIARES_ESPOSA_HIJOS = isset($_POST["NUMERO_DE_FAMILIARES_ESPOSA_HIJOS"])?$_POST["NUMERO_DE_FAMILIARES_ESPOSA_HIJOS"]:"";
$CELULAR_1 = isset($_POST["CELULAR_1"])?$_POST["CELULAR_1"]:"";
$CELULAR_2 = isset($_POST["CELULAR_2"])?$_POST["CELULAR_2"]:"";
$TELEFONO_DE_CASA_1 = isset($_POST["TELEFONO_DE_CASA_1"])?$_POST["TELEFONO_DE_CASA_1"]:"";
$TELEFONO_DE_CASA_2 = isset($_POST["TELEFONO_DE_CASA_2"])?$_POST["TELEFONO_DE_CASA_2"]:"";
$PORCENTAJE_DE_INGLES_HABLADO = isset($_POST["PORCENTAJE_DE_INGLES_HABLADO"])?$_POST["PORCENTAJE_DE_INGLES_HABLADO"]:"";
$PORCENTAJE_DE_INGLES_ESCRITO = isset($_POST["PORCENTAJE_DE_INGLES_ESCRITO"])?$_POST["PORCENTAJE_DE_INGLES_ESCRITO"]:"";
$DOMINIO_DE_OTRO_IDIOMA_Y_PORCENTAJE = isset($_POST["DOMINIO_DE_OTRO_IDIOMA_Y_PORCENTAJE"])?$_POST["DOMINIO_DE_OTRO_IDIOMA_Y_PORCENTAJE"]:"";
$BENEFICIARIO_Y_PORCENTAJE_1_PARA_SEGURO = isset($_POST["BENEFICIARIO_Y_PORCENTAJE_1_PARA_SEGURO"])?$_POST["BENEFICIARIO_Y_PORCENTAJE_1_PARA_SEGURO"]:"";
$BENEFICIARIO_Y_PORCENTAJE_2_PARA_SEGURO = isset($_POST["BENEFICIARIO_Y_PORCENTAJE_2_PARA_SEGURO"])?$_POST["BENEFICIARIO_Y_PORCENTAJE_2_PARA_SEGURO"]:"";
$BENEFICIARIO_YPORCENTAJE_3_PARA_SEGURO = isset($_POST["BENEFICIARIO_YPORCENTAJE_3_PARA_SEGURO"])?$_POST["BENEFICIARIO_YPORCENTAJE_3_PARA_SEGURO"]:"";
$TELEGRAM = isset($_POST["TELEGRAM"])?$_POST["TELEGRAM"]:"";
$TIPO_DE_SANGRE = isset($_POST["TIPO_DE_SANGRE"])?$_POST["TIPO_DE_SANGRE"]:"";
$AUTO = isset($_POST["AUTO"])?$_POST["AUTO"]:"";
$MARCA_DEL_AUTO = isset($_POST["MARCA_DEL_AUTO"])?$_POST["MARCA_DEL_AUTO"]:"";
$SUB_MARCA = isset($_POST["SUB_MARCA"])?$_POST["SUB_MARCA"]:"";
$MODELO = isset($_POST["MODELO"])?$_POST["MODELO"]:"";
$COLOR = isset($_POST["COLOR"])?$_POST["COLOR"]:"";
$PLACAS = isset($_POST["PLACAS"])?$_POST["PLACAS"]:""; 
$IPCORREO1 = isset($_POST["IPCORREO1"])?$_POST["IPCORREO1"]:"";
$IPCORREO2 = isset($_POST["IPCORREO2"])?$_POST["IPCORREO2"]:"";

//include_once (__ROOT1__."/includes/crea_funciones.php");

if($NOMBRE_1 == "" or  $NOMBRE_2 == "" or  $NOMBRE_3 == "" or  $APELLIDO_MATERNO == "" or  $APELLIDO_PATERNO == "" or  $FECHA_DE_NACIMIENTO == "" or  $ANIOS == "" or  $LUGAR_DE_NACIMIENTO_ESTADO_PROVINCIA == "" or  $PAIS_DE_NACIMIENTO == "" or  $ESTADO_CIVIL == "" or  $NUMERO_DE_FAMILIARES_PADRES_HERMANOS == "" or  $NUMERO_DE_FAMILIARES_ESPOSA_HIJOS == "" or  $CELULAR_1 == "" or  $CELULAR_2 == "" or  $TELEFONO_DE_CASA_1 == "" or  $TELEFONO_DE_CASA_2 == "" or  $PORCENTAJE_DE_INGLES_HABLADO == "" or  $PORCENTAJE_DE_INGLES_ESCRITO == "" or  $DOMINIO_DE_OTRO_IDIOMA_Y_PORCENTAJE == "" or  $BENEFICIARIO_Y_PORCENTAJE_1_PARA_SEGURO == "" or  $BENEFICIARIO_Y_PORCENTAJE_2_PARA_SEGURO == "" or  $BENEFICIARIO_YPORCENTAJE_3_PARA_SEGURO == "" or  $TELEGRAM == "" or  $TIPO_DE_SANGRE == "" or  $AUTO == "" or  $MARCA_DEL_AUTO == "" or  $SUB_MARCA == "" or  $MODELO == "" or  $ipersonal1 == "" or  $COLOR == "" or  $PLACAS == ""){
	echo "<P style='color:red; font-size:15px;'>LLENAR TODOS LOS CAMPOS</p>";
}else{
	echo $conexion->guardar_IPERSONAL( $NOMBRE_1 , $NOMBRE_2 , $NOMBRE_3 , $APELLIDO_MATERNO , $APELLIDO_PATERNO ,  $IPCORREO1, $IPCORREO2, $FECHA_DE_NACIMIENTO , $ANIOS , $LUGAR_DE_NACIMIENTO_ESTADO_PROVINCIA , $PAIS_DE_NACIMIENTO , $ESTADO_CIVIL , $NUMERO_DE_FAMILIARES_PADRES_HERMANOS , $NUMERO_DE_FAMILIARES_ESPOSA_HIJOS , $CELULAR_1 , $CELULAR_2 , $TELEFONO_DE_CASA_1 , $TELEFONO_DE_CASA_2 , $PORCENTAJE_DE_INGLES_HABLADO , $PORCENTAJE_DE_INGLES_ESCRITO , $DOMINIO_DE_OTRO_IDIOMA_Y_PORCENTAJE , $BENEFICIARIO_Y_PORCENTAJE_1_PARA_SEGURO , $BENEFICIARIO_Y_PORCENTAJE_2_PARA_SEGURO , $BENEFICIARIO_YPORCENTAJE_3_PARA_SEGURO , $TELEGRAM , $TIPO_DE_SANGRE , $AUTO , $MARCA_DEL_AUTO , $SUB_MARCA , $MODELO , $ipersonal1 , $COLOR , $PLACAS);
}	
	
	
}
elseif($dircasa11 == 'dircasa11'){

$EDIFICIO = isset($_POST["EDIFICIO"])?$_POST["EDIFICIO"]:"";
$calledir1 = isset($_POST["calledir1"])?$_POST["calledir1"]:"";
$NUMERO_EXTERIOR = isset($_POST["NUMERO_EXTERIOR"])?$_POST["NUMERO_EXTERIOR"]:"";
$NUMERO_INTERIOR = isset($_POST["NUMERO_INTERIOR"])?$_POST["NUMERO_INTERIOR"]:"";
$NUMERO_INTERIOR_2 = isset($_POST["NUMERO_INTERIOR_2"])?$_POST["NUMERO_INTERIOR_2"]:"";
$COLONIA = isset($_POST["COLONIA"])?$_POST["COLONIA"]:"";
$ALCALDIA = isset($_POST["ALCALDIA"])?$_POST["ALCALDIA"]:"";
$C_P = isset($_POST["C_P"])?$_POST["C_P"]:"";
$CIUDAD = isset($_POST["CIUDAD"])?$_POST["CIUDAD"]:"";
$ESTADO = isset($_POST["ESTADO"])?$_POST["ESTADO"]:"";
$PAIS = isset($_POST["PAIS"])?$_POST["PAIS"]:"";
$dircasa11 = isset($_POST["dircasa11"])?$_POST["dircasa11"]:"";
$DIRECCION_DE_CASA_1_UBICACION_MAPA = isset($_POST["DIRECCION_DE_CASA_1_UBICACION_MAPA"])?$_POST["DIRECCION_DE_CASA_1_UBICACION_MAPA"]:"";
if($EDIFICIO =="" or $NUMERO_EXTERIOR =="" or $NUMERO_INTERIOR =="" or $NUMERO_INTERIOR_2 =="" or $COLONIA =="" or $ALCALDIA =="" or $C_P =="" or $CIUDAD =="" or $ESTADO =="" or $PAIS =="" or $dircasa11 =="" or $DIRECCION_DE_CASA_1_UBICACION_MAPA ==""){
	echo "<P style='color:red; font-size:15px;'>LLENAR TODOS LOS CAMPOS</p>";
}else{
	echo $conexion->guardar_dircasa1 ($EDIFICIO , $calledir1, $NUMERO_EXTERIOR , $NUMERO_INTERIOR , $NUMERO_INTERIOR_2 , $COLONIA , $ALCALDIA , $C_P , $CIUDAD , $ESTADO , $PAIS , $dircasa11 , $DIRECCION_DE_CASA_1_UBICACION_MAPA );	
}
//include_once (__ROOT1__."/includes/crea_funciones.php");
	
}
elseif($dircasa22 =='dircasa22'){
	
$DIRECCION_CASA_2_EDIFICIO = isset($_POST["DIRECCION_CASA_2_EDIFICIO"])?$_POST["DIRECCION_CASA_2_EDIFICIO"]:"";
$calledir2 = isset($_POST["calledir2"])?$_POST["calledir2"]:"";
$DIRECCION_CASA_2_NUMERO_EXTERIOR = isset($_POST["DIRECCION_CASA_2_NUMERO_EXTERIOR"])?$_POST["DIRECCION_CASA_2_NUMERO_EXTERIOR"]:"";
$DIRECCION_CASA_2_INTERIOR = isset($_POST["DIRECCION_CASA_2_INTERIOR"])?$_POST["DIRECCION_CASA_2_INTERIOR"]:"";
$DIRECCION_CASA_INTERIOR_2 = isset($_POST["DIRECCION_CASA_INTERIOR_2"])?$_POST["DIRECCION_CASA_INTERIOR_2"]:"";
$DIRECCION_CASA_2_COLONIA = isset($_POST["DIRECCION_CASA_2_COLONIA"])?$_POST["DIRECCION_CASA_2_COLONIA"]:"";
$DIRECCION_CASA_2_ALCALDIA = isset($_POST["DIRECCION_CASA_2_ALCALDIA"])?$_POST["DIRECCION_CASA_2_ALCALDIA"]:"";
$DIRECCION_CASA_2_C_P = isset($_POST["DIRECCION_CASA_2_C_P"])?$_POST["DIRECCION_CASA_2_C_P"]:"";
$DIRECCION_CASA_2_CIUDAD = isset($_POST["DIRECCION_CASA_2_CIUDAD"])?$_POST["DIRECCION_CASA_2_CIUDAD"]:"";
$DIRECCION_CASA_2_ESTADO = isset($_POST["DIRECCION_CASA_2_ESTADO"])?$_POST["DIRECCION_CASA_2_ESTADO"]:"";
$DIRECCION_CASA_2_PAIS = isset($_POST["DIRECCION_CASA_2_PAIS"])?$_POST["DIRECCION_CASA_2_PAIS"]:"";
$dircasa22 = isset($_POST["dircasa22"])?$_POST["dircasa22"]:"";
$DIRECCION_DE_CASA_2__UBICACION_EN_EL_MAPA = isset($_POST["DIRECCION_DE_CASA_2__UBICACION_EN_EL_MAPA"])?$_POST["DIRECCION_DE_CASA_2__UBICACION_EN_EL_MAPA"]:"";



if($calledir2 =="" or  $DIRECCION_CASA_2_EDIFICIO =="" or $DIRECCION_CASA_2_NUMERO_EXTERIOR =="" or $DIRECCION_CASA_2_INTERIOR =="" or $DIRECCION_CASA_INTERIOR_2 =="" or $DIRECCION_CASA_2_COLONIA =="" or $DIRECCION_CASA_2_ALCALDIA =="" or $DIRECCION_CASA_2_C_P =="" or $DIRECCION_CASA_2_CIUDAD =="" or $DIRECCION_CASA_2_ESTADO =="" or $DIRECCION_CASA_2_PAIS =="" or $dircasa22 =="" or $DIRECCION_DE_CASA_2__UBICACION_EN_EL_MAPA ==""  ){
	echo "<P style='color:red; font-size:15px;'>LLENAR TODOS LOS CAMPOS</p>";
}else{

	echo $conexion->guardar_dircasa2( $DIRECCION_CASA_2_EDIFICIO , $calledir2, $DIRECCION_CASA_2_NUMERO_EXTERIOR , $DIRECCION_CASA_2_INTERIOR , $DIRECCION_CASA_INTERIOR_2 , $DIRECCION_CASA_2_COLONIA , $DIRECCION_CASA_2_ALCALDIA , $DIRECCION_CASA_2_C_P , $DIRECCION_CASA_2_CIUDAD , $DIRECCION_CASA_2_ESTADO , $DIRECCION_CASA_2_PAIS , $dircasa22 , $DIRECCION_DE_CASA_2__UBICACION_EN_EL_MAPA );	
}
	//include_once (__ROOT1__."/includes/crea_funciones.php");
}
elseif($F1CERCANO1 =='F1CERCANO1'){
	
	
$FAMILIAR_1_PARENTESCO = isset($_POST["FAMILIAR_1_PARENTESCO"])?$_POST["FAMILIAR_1_PARENTESCO"]:"";
$FAMILIAR_1_NOMBRE_1 = isset($_POST["FAMILIAR_1_NOMBRE_1"])?$_POST["FAMILIAR_1_NOMBRE_1"]:"";
$FAMILIAR_1_NOMBRE_2 = isset($_POST["FAMILIAR_1_NOMBRE_2"])?$_POST["FAMILIAR_1_NOMBRE_2"]:"";
$FAMILIAR_1_APELLIDO_MATERNO = isset($_POST["FAMILIAR_1_APELLIDO_MATERNO"])?$_POST["FAMILIAR_1_APELLIDO_MATERNO"]:"";
$FAMILIAR_1_APELLIDO_PATERNO = isset($_POST["FAMILIAR_1_APELLIDO_PATERNO"])?$_POST["FAMILIAR_1_APELLIDO_PATERNO"]:"";
$FAMILIAR_1_CELULAR_1 = isset($_POST["FAMILIAR_1_CELULAR_1"])?$_POST["FAMILIAR_1_CELULAR_1"]:"";
$FAMILIAR_1_CELULAR_2 = isset($_POST["FAMILIAR_1_CELULAR_2"])?$_POST["FAMILIAR_1_CELULAR_2"]:"";
$FAMILIAR_1_TELEFONO_DE_CASA_I = isset($_POST["FAMILIAR_1_TELEFONO_DE_CASA_I"])?$_POST["FAMILIAR_1_TELEFONO_DE_CASA_I"]:"";
$FAMILIAR_1_CORREO_ELECTRONICO = isset($_POST["FAMILIAR_1_CORREO_ELECTRONICO"])?$_POST["FAMILIAR_1_CORREO_ELECTRONICO"]:"";
$FAMILIAR_1_EDIFICIO = isset($_POST["FAMILIAR_1_EDIFICIO"])?$_POST["FAMILIAR_1_EDIFICIO"]:"";
$FAMILIAR_1_NUMERO_CALLE = isset($_POST["FAMILIAR_1_NUMERO_CALLE"])?$_POST["FAMILIAR_1_NUMERO_CALLE"]:"";
$FAMILIAR_1_NUMERO_EXTERIOR = isset($_POST["FAMILIAR_1_NUMERO_EXTERIOR"])?$_POST["FAMILIAR_1_NUMERO_EXTERIOR"]:"";
$FAMILIAR_1_NUMERO_INTERIOR = isset($_POST["FAMILIAR_1_NUMERO_INTERIOR"])?$_POST["FAMILIAR_1_NUMERO_INTERIOR"]:"";
$FAMILIAR_1_NUMER__INTERIOR_2 = isset($_POST["FAMILIAR_1_NUMER__INTERIOR_2"])?$_POST["FAMILIAR_1_NUMER__INTERIOR_2"]:"";
$FAMILIAR_1_COLONIA = isset($_POST["FAMILIAR_1_COLONIA"])?$_POST["FAMILIAR_1_COLONIA"]:"";
$FAMILIAR_1_ALCALDIA = isset($_POST["FAMILIAR_1_ALCALDIA"])?$_POST["FAMILIAR_1_ALCALDIA"]:"";
$FAMILIAR_1_C_P = isset($_POST["FAMILIAR_1_C_P"])?$_POST["FAMILIAR_1_C_P"]:"";
$FAMILIAR_1_CIUDAD = isset($_POST["FAMILIAR_1_CIUDAD"])?$_POST["FAMILIAR_1_CIUDAD"]:"";
$FAMILIAR_1_ESTADO = isset($_POST["FAMILIAR_1_ESTADO"])?$_POST["FAMILIAR_1_ESTADO"]:"";
$FAMILIAR_1_PAIS = isset($_POST["FAMILIAR_1_PAIS"])?$_POST["FAMILIAR_1_PAIS"]:"";
$F1CERCANO1 = isset($_POST["F1CERCANO1"])?$_POST["F1CERCANO1"]:"";
$FAMILIAR_1_UBICACION__EN_EL_MAPA = isset($_POST["FAMILIAR_1_UBICACION__EN_EL_MAPA"])?$_POST["FAMILIAR_1_UBICACION__EN_EL_MAPA"]:""; 

if($FAMILIAR_1_PARENTESCO =="" or $FAMILIAR_1_NOMBRE_1 =="" or $FAMILIAR_1_NOMBRE_2 =="" or $FAMILIAR_1_APELLIDO_MATERNO =="" or $FAMILIAR_1_APELLIDO_PATERNO =="" or $FAMILIAR_1_CELULAR_1 =="" or $FAMILIAR_1_CELULAR_2 =="" or $FAMILIAR_1_TELEFONO_DE_CASA_I =="" or $FAMILIAR_1_CORREO_ELECTRONICO =="" or $FAMILIAR_1_EDIFICIO =="" or $FAMILIAR_1_NUMERO_CALLE =="" or $FAMILIAR_1_NUMERO_EXTERIOR =="" or $FAMILIAR_1_NUMERO_INTERIOR =="" or $FAMILIAR_1_NUMER__INTERIOR_2 =="" or $FAMILIAR_1_COLONIA =="" or $FAMILIAR_1_ALCALDIA =="" or $FAMILIAR_1_C_P =="" or $FAMILIAR_1_CIUDAD =="" or $FAMILIAR_1_ESTADO =="" or $FAMILIAR_1_PAIS =="" or $F1CERCANO1 =="" or $FAMILIAR_1_UBICACION__EN_EL_MAPA =="" ){
	
	echo "<P style='color:red; font-size:15px;'>LLENAR TODOS LOS CAMPOS</p>";
}else{
	
	echo $conexion->guardar_f1cercano($FAMILIAR_1_PARENTESCO , $FAMILIAR_1_NOMBRE_1 , $FAMILIAR_1_NOMBRE_2 , $FAMILIAR_1_APELLIDO_MATERNO , $FAMILIAR_1_APELLIDO_PATERNO , $FAMILIAR_1_CELULAR_1 , $FAMILIAR_1_CELULAR_2 , $FAMILIAR_1_TELEFONO_DE_CASA_I , $FAMILIAR_1_CORREO_ELECTRONICO , $FAMILIAR_1_EDIFICIO , $FAMILIAR_1_NUMERO_CALLE , $FAMILIAR_1_NUMERO_EXTERIOR , $FAMILIAR_1_NUMERO_INTERIOR , $FAMILIAR_1_NUMER__INTERIOR_2 , $FAMILIAR_1_COLONIA , $FAMILIAR_1_ALCALDIA , $FAMILIAR_1_C_P , $FAMILIAR_1_CIUDAD , $FAMILIAR_1_ESTADO , $FAMILIAR_1_PAIS , $F1CERCANO1 , $FAMILIAR_1_UBICACION__EN_EL_MAPA );
}
	
	
//include_once (__ROOT1__."/includes/crea_funciones.php");	
}
elseif($F2CERCANO2 == 'F2CERCANO2'){
$FAMILIAR2_PARENTESCO = isset($_POST["FAMILIAR2_PARENTESCO"])?$_POST["FAMILIAR2_PARENTESCO"]:"";
$FAMILIAR2_NOMBRE_1 = isset($_POST["FAMILIAR2_NOMBRE_1"])?$_POST["FAMILIAR2_NOMBRE_1"]:"";
$FAMILIAR2_NOMBRE_2 = isset($_POST["FAMILIAR2_NOMBRE_2"])?$_POST["FAMILIAR2_NOMBRE_2"]:"";
$FAMILIAR2_APELLIDO_MATERNO = isset($_POST["FAMILIAR2_APELLIDO_MATERNO"])?$_POST["FAMILIAR2_APELLIDO_MATERNO"]:"";
$FAMILIAR2_APELLIDO_PATERNO = isset($_POST["FAMILIAR2_APELLIDO_PATERNO"])?$_POST["FAMILIAR2_APELLIDO_PATERNO"]:"";
$FAMILIAR2_CELULAR_1 = isset($_POST["FAMILIAR2_CELULAR_1"])?$_POST["FAMILIAR2_CELULAR_1"]:"";
$FAMILIAR2_CELULAR_2 = isset($_POST["FAMILIAR2_CELULAR_2"])?$_POST["FAMILIAR2_CELULAR_2"]:"";
$FAMILIAR2_TELEFONO_DE_CASA_I = isset($_POST["FAMILIAR2_TELEFONO_DE_CASA_I"])?$_POST["FAMILIAR2_TELEFONO_DE_CASA_I"]:"";
$FAMILIAR2_CORREO_ELECTRONICO = isset($_POST["FAMILIAR2_CORREO_ELECTRONICO"])?$_POST["FAMILIAR2_CORREO_ELECTRONICO"]:"";
$FAMILIAR2_EDIFICIO = isset($_POST["FAMILIAR2_EDIFICIO"])?$_POST["FAMILIAR2_EDIFICIO"]:"";
$FAMILIAR2_CALLE = isset($_POST["FAMILIAR2_CALLE"])?$_POST["FAMILIAR2_CALLE"]:"";
$FAMILIAR2_NUMERO_EXTERIOR = isset($_POST["FAMILIAR2_NUMERO_EXTERIOR"])?$_POST["FAMILIAR2_NUMERO_EXTERIOR"]:"";
$FAMILIAR2_NUMERO_INTERIOR = isset($_POST["FAMILIAR2_NUMERO_INTERIOR"])?$_POST["FAMILIAR2_NUMERO_INTERIOR"]:"";
$FAMILIAR2_NUMER_INTERIOR_2 = isset($_POST["FAMILIAR2_NUMER_INTERIOR_2"])?$_POST["FAMILIAR2_NUMER_INTERIOR_2"]:"";
$FAMILIAR2_COLONIA = isset($_POST["FAMILIAR2_COLONIA"])?$_POST["FAMILIAR2_COLONIA"]:"";
$FAMILIAR2_ALCALDIA = isset($_POST["FAMILIAR2_ALCALDIA"])?$_POST["FAMILIAR2_ALCALDIA"]:"";
$FAMILIAR2_C_P = isset($_POST["FAMILIAR2_C_P"])?$_POST["FAMILIAR2_C_P"]:"";
$FAMILIAR2_CIUDAD = isset($_POST["FAMILIAR2_CIUDAD"])?$_POST["FAMILIAR2_CIUDAD"]:"";
$FAMILIAR2_ESTADO = isset($_POST["FAMILIAR2_ESTADO"])?$_POST["FAMILIAR2_ESTADO"]:"";
$FAMILIAR2_PAIS = isset($_POST["FAMILIAR2_PAIS"])?$_POST["FAMILIAR2_PAIS"]:"";
$F2CERCANO2 = isset($_POST["F2CERCANO2"])?$_POST["F2CERCANO2"]:"";
$FAMILIAR2_UBICACION_EN_EL_MAPA = isset($_POST["FAMILIAR2_UBICACION_EN_EL_MAPA"])?$_POST["FAMILIAR2_UBICACION_EN_EL_MAPA"]:""; 
if($FAMILIAR2_PARENTESCO =="" or $FAMILIAR2_NOMBRE_1 =="" or $FAMILIAR2_NOMBRE_2 =="" or $FAMILIAR2_APELLIDO_MATERNO =="" or $FAMILIAR2_APELLIDO_PATERNO =="" or $FAMILIAR2_CELULAR_1 =="" or $FAMILIAR2_CELULAR_2 =="" or $FAMILIAR2_TELEFONO_DE_CASA_I =="" or $FAMILIAR2_CORREO_ELECTRONICO =="" or $FAMILIAR2_EDIFICIO =="" or $FAMILIAR2_CALLE =="" or $FAMILIAR2_NUMERO_EXTERIOR =="" or $FAMILIAR2_NUMERO_INTERIOR =="" or $FAMILIAR2_NUMER_INTERIOR_2 =="" or $FAMILIAR2_COLONIA =="" or $FAMILIAR2_ALCALDIA =="" or $FAMILIAR2_C_P =="" or $FAMILIAR2_CIUDAD =="" or $FAMILIAR2_ESTADO =="" or $FAMILIAR2_PAIS =="" or $F2CERCANO2 =="" or $FAMILIAR2_UBICACION_EN_EL_MAPA =="" ){
//include_once (__ROOT1__."/includes/crea_funciones.php");
	
	echo "<P style='color:red; font-size:15px;'>LLENAR TODOS LOS CAMPOS</p>";
	
}else{
	
	echo $conexion->guardar_f2cercano( $FAMILIAR2_PARENTESCO , $FAMILIAR2_NOMBRE_1 , $FAMILIAR2_NOMBRE_2 , $FAMILIAR2_APELLIDO_MATERNO , $FAMILIAR2_APELLIDO_PATERNO , $FAMILIAR2_CELULAR_1 , $FAMILIAR2_CELULAR_2 , $FAMILIAR2_TELEFONO_DE_CASA_I , $FAMILIAR2_CORREO_ELECTRONICO , $FAMILIAR2_EDIFICIO , $FAMILIAR2_CALLE , $FAMILIAR2_NUMERO_EXTERIOR , $FAMILIAR2_NUMERO_INTERIOR , $FAMILIAR2_NUMER_INTERIOR_2 , $FAMILIAR2_COLONIA , $FAMILIAR2_ALCALDIA , $FAMILIAR2_C_P , $FAMILIAR2_CIUDAD , $FAMILIAR2_ESTADO , $FAMILIAR2_PAIS , $F2CERCANO2 , $FAMILIAR2_UBICACION_EN_EL_MAPA );
}


	
}
elseif($F3CERCANO3 == 'F3CERCANO3'){
$FAMILIAR3_PARENTESCO = isset($_POST["FAMILIAR3_PARENTESCO"])?$_POST["FAMILIAR3_PARENTESCO"]:"";
$FAMILIAR3_NOMBRE_1 = isset($_POST["FAMILIAR3_NOMBRE_1"])?$_POST["FAMILIAR3_NOMBRE_1"]:"";
$FAMILIAR3_NOMBRE_2 = isset($_POST["FAMILIAR3_NOMBRE_2"])?$_POST["FAMILIAR3_NOMBRE_2"]:"";
$FAMILIAR3_APELLIDO_MATERNO = isset($_POST["FAMILIAR3_APELLIDO_MATERNO"])?$_POST["FAMILIAR3_APELLIDO_MATERNO"]:"";
$FAMILIAR3_APELLIDO_PATERNO = isset($_POST["FAMILIAR3_APELLIDO_PATERNO"])?$_POST["FAMILIAR3_APELLIDO_PATERNO"]:"";
$FAMILIAR3_CELULAR_1 = isset($_POST["FAMILIAR3_CELULAR_1"])?$_POST["FAMILIAR3_CELULAR_1"]:"";
$FAMILIAR3_CELULAR_2 = isset($_POST["FAMILIAR3_CELULAR_2"])?$_POST["FAMILIAR3_CELULAR_2"]:"";
$FAMILIAR3_TELEFONO_DE_CASA_I = isset($_POST["FAMILIAR3_TELEFONO_DE_CASA_I"])?$_POST["FAMILIAR3_TELEFONO_DE_CASA_I"]:"";
$FAMILIAR3_CORREO_ELECTRONICO = isset($_POST["FAMILIAR3_CORREO_ELECTRONICO"])?$_POST["FAMILIAR3_CORREO_ELECTRONICO"]:"";
$FAMILIAR3_EDIFICIO = isset($_POST["FAMILIAR3_EDIFICIO"])?$_POST["FAMILIAR3_EDIFICIO"]:"";
$FAMILIAR3_calle = isset($_POST["FAMILIAR3_calle"])?$_POST["FAMILIAR3_calle"]:"";
$FAMILIAR3_NUMERO_EXTERIOR = isset($_POST["FAMILIAR3_NUMERO_EXTERIOR"])?$_POST["FAMILIAR3_NUMERO_EXTERIOR"]:"";
$FAMILIAR3_NUMERO_INTERIOR = isset($_POST["FAMILIAR3_NUMERO_INTERIOR"])?$_POST["FAMILIAR3_NUMERO_INTERIOR"]:"";
$FAMILIAR3_NUMER_INTERIOR_2 = isset($_POST["FAMILIAR3_NUMER_INTERIOR_2"])?$_POST["FAMILIAR3_NUMER_INTERIOR_2"]:"";
$FAMILIAR3_COLONIA = isset($_POST["FAMILIAR3_COLONIA"])?$_POST["FAMILIAR3_COLONIA"]:"";
$FAMILIAR3_ALCALDIA = isset($_POST["FAMILIAR3_ALCALDIA"])?$_POST["FAMILIAR3_ALCALDIA"]:"";
$FAMILIAR3_C_P = isset($_POST["FAMILIAR3_C_P"])?$_POST["FAMILIAR3_C_P"]:"";
$FAMILIAR3_CIUDAD = isset($_POST["FAMILIAR3_CIUDAD"])?$_POST["FAMILIAR3_CIUDAD"]:"";
$FAMILIAR3_ESTADO = isset($_POST["FAMILIAR3_ESTADO"])?$_POST["FAMILIAR3_ESTADO"]:"";
$FAMILIAR3_PAIS = isset($_POST["FAMILIAR3_PAIS"])?$_POST["FAMILIAR3_PAIS"]:"";
$F3CERCANO3 = isset($_POST["F3CERCANO3"])?$_POST["F3CERCANO3"]:"";
$FAMILIAR3_UBICACION_EN_EL_MAPA = isset($_POST["FAMILIAR3_UBICACION_EN_EL_MAPA"])?$_POST["FAMILIAR3_UBICACION_EN_EL_MAPA"]:""; 

	if( $FAMILIAR3_PARENTESCO =="" or $FAMILIAR3_NOMBRE_1 =="" or $FAMILIAR3_NOMBRE_2 =="" or $FAMILIAR3_APELLIDO_MATERNO =="" or $FAMILIAR3_APELLIDO_PATERNO =="" or $FAMILIAR3_CELULAR_1 =="" or $FAMILIAR3_CELULAR_2 =="" or $FAMILIAR3_TELEFONO_DE_CASA_I =="" or $FAMILIAR3_CORREO_ELECTRONICO =="" or $FAMILIAR3_EDIFICIO =="" or $FAMILIAR3_calle =="" or $FAMILIAR3_NUMERO_EXTERIOR =="" or $FAMILIAR3_NUMERO_INTERIOR =="" or $FAMILIAR3_NUMER_INTERIOR_2 =="" or $FAMILIAR3_COLONIA =="" or $FAMILIAR3_ALCALDIA =="" or $FAMILIAR3_C_P =="" or $FAMILIAR3_CIUDAD =="" or $FAMILIAR3_ESTADO =="" or $FAMILIAR3_PAIS =="" or $F3CERCANO3 =="" or $FAMILIAR3_UBICACION_EN_EL_MAPA =="" ){
	echo "<P style='color:red; font-size:15px;'>LLENAR TODOS LOS CAMPOS</p>";
	}else{
	echo $conexion->guardar_f3cercano ($FAMILIAR3_PARENTESCO , $FAMILIAR3_NOMBRE_1 , $FAMILIAR3_NOMBRE_2 , $FAMILIAR3_APELLIDO_MATERNO , $FAMILIAR3_APELLIDO_PATERNO , $FAMILIAR3_CELULAR_1 , $FAMILIAR3_CELULAR_2 , $FAMILIAR3_TELEFONO_DE_CASA_I , $FAMILIAR3_CORREO_ELECTRONICO , $FAMILIAR3_EDIFICIO , $FAMILIAR3_calle , $FAMILIAR3_NUMERO_EXTERIOR , $FAMILIAR3_NUMERO_INTERIOR , $FAMILIAR3_NUMER_INTERIOR_2 , $FAMILIAR3_COLONIA , $FAMILIAR3_ALCALDIA , $FAMILIAR3_C_P , $FAMILIAR3_CIUDAD , $FAMILIAR3_ESTADO , $FAMILIAR3_PAIS , $F3CERCANO3 , $FAMILIAR3_UBICACION_EN_EL_MAPA );
	}
//include_once (__ROOT1__."/includes/crea_funciones.php");
	
}
elseif($F4CERCANO4 == 'F4CERCANO4'){
$FAMILIAR4_PARENTESCO = isset($_POST["FAMILIAR4_PARENTESCO"])?$_POST["FAMILIAR4_PARENTESCO"]:"";
$FAMILIAR4_NOMBRE_1 = isset($_POST["FAMILIAR4_NOMBRE_1"])?$_POST["FAMILIAR4_NOMBRE_1"]:"";
$FAMILIAR4_NOMBRE_2 = isset($_POST["FAMILIAR4_NOMBRE_2"])?$_POST["FAMILIAR4_NOMBRE_2"]:"";
$FAMILIAR4_APELLIDO_MATERNO = isset($_POST["FAMILIAR4_APELLIDO_MATERNO"])?$_POST["FAMILIAR4_APELLIDO_MATERNO"]:"";
$FAMILIAR4_APELLIDO_PATERNO = isset($_POST["FAMILIAR4_APELLIDO_PATERNO"])?$_POST["FAMILIAR4_APELLIDO_PATERNO"]:"";
$FAMILIAR4_CELULAR_1 = isset($_POST["FAMILIAR4_CELULAR_1"])?$_POST["FAMILIAR4_CELULAR_1"]:"";
$FAMILIAR4_CELULAR_2 = isset($_POST["FAMILIAR4_CELULAR_2"])?$_POST["FAMILIAR4_CELULAR_2"]:"";
$FAMILIAR4_TELEFONO_DE_CASA_I = isset($_POST["FAMILIAR4_TELEFONO_DE_CASA_I"])?$_POST["FAMILIAR4_TELEFONO_DE_CASA_I"]:"";
$FAMILIAR4_CORREO_ELECTRONICO = isset($_POST["FAMILIAR4_CORREO_ELECTRONICO"])?$_POST["FAMILIAR4_CORREO_ELECTRONICO"]:"";
$FAMILIAR4_EDIFICIO = isset($_POST["FAMILIAR4_EDIFICIO"])?$_POST["FAMILIAR4_EDIFICIO"]:"";
$FAMILIAR4_CALLE = isset($_POST["FAMILIAR4_CALLE"])?$_POST["FAMILIAR4_CALLE"]:"";
$FAMILIAR4_NUMERO_EXTERIOR = isset($_POST["FAMILIAR4_NUMERO_EXTERIOR"])?$_POST["FAMILIAR4_NUMERO_EXTERIOR"]:"";
$FAMILIAR4_NUMERO_INTERIOR = isset($_POST["FAMILIAR4_NUMERO_INTERIOR"])?$_POST["FAMILIAR4_NUMERO_INTERIOR"]:"";
$FAMILIAR4_NUMER__INTERIOR_2 = isset($_POST["FAMILIAR4_NUMER__INTERIOR_2"])?$_POST["FAMILIAR4_NUMER__INTERIOR_2"]:"";
$FAMILIAR4_COLONIA = isset($_POST["FAMILIAR4_COLONIA"])?$_POST["FAMILIAR4_COLONIA"]:"";
$FAMILIAR4_ALCALDIA = isset($_POST["FAMILIAR4_ALCALDIA"])?$_POST["FAMILIAR4_ALCALDIA"]:"";
$FAMILIAR4_C_P = isset($_POST["FAMILIAR4_C_P"])?$_POST["FAMILIAR4_C_P"]:"";
$FAMILIAR4_CIUDAD = isset($_POST["FAMILIAR4_CIUDAD"])?$_POST["FAMILIAR4_CIUDAD"]:"";
$FAMILIAR4_ESTADO = isset($_POST["FAMILIAR4_ESTADO"])?$_POST["FAMILIAR4_ESTADO"]:"";
$FAMILIAR4_PAIS = isset($_POST["FAMILIAR4_PAIS"])?$_POST["FAMILIAR4_PAIS"]:"";
$F4CERCANO4 = isset($_POST["F4CERCANO4"])?$_POST["F4CERCANO4"]:"";
$FAMILIAR4_UBICACION_EN_EL_MAPA = isset($_POST["FAMILIAR4_UBICACION_EN_EL_MAPA"])?$_POST["FAMILIAR4_UBICACION_EN_EL_MAPA"]:""; 

	if($FAMILIAR4_PARENTESCO =="" or $FAMILIAR4_NOMBRE_1 =="" or $FAMILIAR4_NOMBRE_2 =="" or $FAMILIAR4_APELLIDO_MATERNO =="" or $FAMILIAR4_APELLIDO_PATERNO =="" or $FAMILIAR4_CELULAR_1 =="" or $FAMILIAR4_CELULAR_2 =="" or $FAMILIAR4_TELEFONO_DE_CASA_I =="" or $FAMILIAR4_CORREO_ELECTRONICO =="" or $FAMILIAR4_EDIFICIO =="" or $FAMILIAR4_CALLE =="" or $FAMILIAR4_NUMERO_EXTERIOR =="" or $FAMILIAR4_NUMERO_INTERIOR =="" or $FAMILIAR4_NUMER__INTERIOR_2 =="" or $FAMILIAR4_COLONIA =="" or $FAMILIAR4_ALCALDIA =="" or $FAMILIAR4_C_P =="" or $FAMILIAR4_CIUDAD =="" or $FAMILIAR4_ESTADO =="" or $FAMILIAR4_PAIS =="" or $F4CERCANO4 =="" or $FAMILIAR4_UBICACION_EN_EL_MAPA =="" ){
	echo "<P style='color:red; font-size:15px;'>LLENAR TODOS LOS CAMPOS</p>";		
	}else{
	echo $conexion->guardar_f4cercano($FAMILIAR4_PARENTESCO , $FAMILIAR4_NOMBRE_1 , $FAMILIAR4_NOMBRE_2 , $FAMILIAR4_APELLIDO_MATERNO , $FAMILIAR4_APELLIDO_PATERNO , $FAMILIAR4_CELULAR_1 , $FAMILIAR4_CELULAR_2 , $FAMILIAR4_TELEFONO_DE_CASA_I , $FAMILIAR4_CORREO_ELECTRONICO , $FAMILIAR4_EDIFICIO , $FAMILIAR4_CALLE , $FAMILIAR4_NUMERO_EXTERIOR , $FAMILIAR4_NUMERO_INTERIOR , $FAMILIAR4_NUMER__INTERIOR_2 , $FAMILIAR4_COLONIA , $FAMILIAR4_ALCALDIA , $FAMILIAR4_C_P , $FAMILIAR4_CIUDAD , $FAMILIAR4_ESTADO , $FAMILIAR4_PAIS , $F4CERCANO4 , $FAMILIAR4_UBICACION_EN_EL_MAPA );
	}
	
//include_once (__ROOT1__."/includes/crea_funciones.php");	
}
elseif($habilidades1 == 'habilidades1'){
$LUNES = isset($_POST["LUNES"])?1:0;
$LHORARIOS = isset($_POST["LHORARIOS"])?$_POST["LHORARIOS"]:"";
$LOBSERBACIONES = isset($_POST["LOBSERBACIONES"])?$_POST["LOBSERBACIONES"]:"";
$MARTES = isset($_POST["MARTES"])?1:0;
$MAHORARIOS = isset($_POST["MAHORARIOS"])?$_POST["MAHORARIOS"]:"";
$MAOBSERBACIONES = isset($_POST["MAOBSERBACIONES"])?$_POST["MAOBSERBACIONES"]:"";
$MIERCOLES = isset($_POST["MIERCOLES"])?$_POST["MIERCOLES"]:"";
$MIHORARIOS = isset($_POST["MIHORARIOS"])?$_POST["MIHORARIOS"]:"";
$MIOBSERBACIONES = isset($_POST["MIOBSERBACIONES"])?$_POST["MIOBSERBACIONES"]:"";
$JUEVES = isset($_POST["JUEVES"])?$_POST["JUEVES"]:"";
$JHORARIOS = isset($_POST["JHORARIOS"])?$_POST["JHORARIOS"]:"";
$JOBSERBACIONES = isset($_POST["JOBSERBACIONES"])?$_POST["JOBSERBACIONES"]:"";
$VIERNES = isset($_POST["VIERNES"])?$_POST["VIERNES"]:"";
$VHORARIOS = isset($_POST["VHORARIOS"])?$_POST["VHORARIOS"]:"";
$VOBSERBACIONES = isset($_POST["VOBSERBACIONES"])?$_POST["VOBSERBACIONES"]:"";
$SABADO = isset($_POST["SABADO"])?$_POST["SABADO"]:"";
$SHORARIOS = isset($_POST["SHORARIOS"])?$_POST["SHORARIOS"]:"";
$SOBSERBACIONES = isset($_POST["SOBSERBACIONES"])?$_POST["SOBSERBACIONES"]:"";
$DOMINGO = isset($_POST["DOMINGO"])?$_POST["DOMINGO"]:"";
$DHORARIOS = isset($_POST["DHORARIOS"])?$_POST["DHORARIOS"]:"";
$DOBSERBACIONES = isset($_POST["DOBSERBACIONES"])?$_POST["DOBSERBACIONES"]:"";
$FIESTA_MEXICANA = isset($_POST["FIESTA_MEXICANA"])?$_POST["FIESTA_MEXICANA"]:"";
$EFIESTA_MEXICANA = isset($_POST["EFIESTA_MEXICANA"])?$_POST["EFIESTA_MEXICANA"]:"";
$OFIESTA_MEXICANA = isset($_POST["OFIESTA_MEXICANA"])?$_POST["OFIESTA_MEXICANA"]:"";
$JEOPARDY = isset($_POST["JEOPARDY"])?$_POST["JEOPARDY"]:"";
$EJEOPARDY = isset($_POST["EJEOPARDY"])?$_POST["EJEOPARDY"]:"";
$OJEOPARDY = isset($_POST["OJEOPARDY"])?$_POST["OJEOPARDY"]:"";
$RALLYS = isset($_POST["RALLYS"])?$_POST["RALLYS"]:"";
$ERALLYS = isset($_POST["ERALLYS"])?$_POST["ERALLYS"]:"";
$ORALLYS = isset($_POST["ORALLYS"])?$_POST["ORALLYS"]:"";
$a100_MEXICANOS_DIJIERON = isset($_POST["a100_MEXICANOS_DIJIERON"])?$_POST["a100_MEXICANOS_DIJIERON"]:"";
$E100_MEXICANOS_DIJIERON = isset($_POST["E100_MEXICANOS_DIJIERON"])?$_POST["E100_MEXICANOS_DIJIERON"]:"";
$O100_MEXICANOS_DIJIERON = isset($_POST["O100_MEXICANOS_DIJIERON"])?$_POST["O100_MEXICANOS_DIJIERON"]:"";
$NOCHE_DE_LAS_ESTRELLAS = isset($_POST["NOCHE_DE_LAS_ESTRELLAS"])?$_POST["NOCHE_DE_LAS_ESTRELLAS"]:"";
$ENOCHE_DE_LAS_ESTRELLAS = isset($_POST["ENOCHE_DE_LAS_ESTRELLAS"])?$_POST["ENOCHE_DE_LAS_ESTRELLAS"]:"";
$ONOCHE_DE_LAS_ESTRELLAS = isset($_POST["ONOCHE_DE_LAS_ESTRELLAS"])?$_POST["ONOCHE_DE_LAS_ESTRELLAS"]:"";
$HANDS_UP = isset($_POST["HANDS_UP"])?$_POST["HANDS_UP"]:"";
$EHANDS_UP = isset($_POST["EHANDS_UP"])?$_POST["EHANDS_UP"]:"";
$OHANDS_UP = isset($_POST["OHANDS_UP"])?$_POST["OHANDS_UP"]:"";
$CALAMAR = isset($_POST["CALAMAR"])?$_POST["CALAMAR"]:"";
$ECALAMAR = isset($_POST["ECALAMAR"])?$_POST["ECALAMAR"]:"";
$OCALAMAR = isset($_POST["OCALAMAR"])?$_POST["OCALAMAR"]:"";
$CRUCERO = isset($_POST["CRUCERO"])?$_POST["CRUCERO"]:"";
$ECRUCERO = isset($_POST["ECRUCERO"])?$_POST["ECRUCERO"]:"";
$OCRUCERO = isset($_POST["OCRUCERO"])?$_POST["OCRUCERO"]:"";
$MAESTRO_DE_CEREMONIAS = isset($_POST["MAESTRO_DE_CEREMONIAS"])?$_POST["MAESTRO_DE_CEREMONIAS"]:"";
$EMAESTRO_DE_CEREMONIAS = isset($_POST["EMAESTRO_DE_CEREMONIAS"])?$_POST["EMAESTRO_DE_CEREMONIAS"]:"";
$OMAESTRO_DE_CEREMONIAS = isset($_POST["OMAESTRO_DE_CEREMONIAS"])?$_POST["OMAESTRO_DE_CEREMONIAS"]:"";
$CASINO = isset($_POST["CASINO"])?$_POST["CASINO"]:"";
$ECASINO = isset($_POST["ECASINO"])?$_POST["ECASINO"]:"";
$OCASINO = isset($_POST["OCASINO"])?$_POST["OCASINO"]:"";
$CUBILETE = isset($_POST["CUBILETE"])?$_POST["CUBILETE"]:"";
$ECUBILETE = isset($_POST["ECUBILETE"])?$_POST["ECUBILETE"]:"";
$OCUBILETE = isset($_POST["OCUBILETE"])?$_POST["OCUBILETE"]:"";
$CRABS = isset($_POST["CRABS"])?$_POST["CRABS"]:"";
$ECRABS = isset($_POST["ECRABS"])?$_POST["ECRABS"]:"";
$OCRABS = isset($_POST["OCRABS"])?$_POST["OCRABS"]:"";
$RULETA = isset($_POST["RULETA"])?$_POST["RULETA"]:"";
$ERULETA = isset($_POST["ERULETA"])?$_POST["ERULETA"]:"";
$ORULETA = isset($_POST["ORULETA"])?$_POST["ORULETA"]:"";
$BLACK_JACK = isset($_POST["BLACK_JACK"])?$_POST["BLACK_JACK"]:"";
$EBLACK_JACK = isset($_POST["EBLACK_JACK"])?$_POST["EBLACK_JACK"]:"";
$OBLACK_JACK = isset($_POST["OBLACK_JACK"])?$_POST["OBLACK_JACK"]:"";
$INFLABLES = isset($_POST["INFLABLES"])?$_POST["INFLABLES"]:"";
$EINFLABLES = isset($_POST["EINFLABLES"])?$_POST["EINFLABLES"]:"";
$OINFLABLES = isset($_POST["OINFLABLES"])?$_POST["OINFLABLES"]:"";
$AAA = isset($_POST["AAA"])?$_POST["AAA"]:"";
$AAAA = isset($_POST["AAAA"])?$_POST["AAAA"]:"";
$EAAAA = isset($_POST["EAAAA"])?$_POST["EAAAA"]:"";
$OAAAA = isset($_POST["OAAAA"])?$_POST["OAAAA"]:"";
$BBB = isset($_POST["BBB"])?$_POST["BBB"]:"";
$BBBB = isset($_POST["BBBB"])?$_POST["BBBB"]:"";
$EBBB = isset($_POST["EBBB"])?$_POST["EBBB"]:"";
$OBBB = isset($_POST["OBBB"])?$_POST["OBBB"]:"";
$CCC = isset($_POST["CCC"])?$_POST["CCC"]:"";
$CCCC = isset($_POST["CCCC"])?$_POST["CCCC"]:"";
$ECCC = isset($_POST["ECCC"])?$_POST["ECCC"]:"";
$OCCC = isset($_POST["OCCC"])?$_POST["OCCC"]:"";
$DDD = isset($_POST["DDD"])?$_POST["DDD"]:"";
$EDDD = isset($_POST["EDDD"])?$_POST["EDDD"]:"";
$ODDD = isset($_POST["ODDD"])?$_POST["ODDD"]:"";
$EEE = isset($_POST["EEE"])?$_POST["EEE"]:"";
$EEEEE = isset($_POST["EEEEE"])?$_POST["EEEEE"]:"";
$EEEE = isset($_POST["EEEE"])?$_POST["EEEE"]:"";
$OEEE = isset($_POST["OEEE"])?$_POST["OEEE"]:"";
$FFF = isset($_POST["FFF"])?$_POST["FFF"]:"";
$FFFF = isset($_POST["FFFF"])?$_POST["FFFF"]:"";
$EFFF = isset($_POST["EFFF"])?$_POST["EFFF"]:"";
$OFFF = isset($_POST["OFFF"])?$_POST["OFFF"]:"";
$GGG = isset($_POST["GGG"])?$_POST["GGG"]:"";
$GGGG = isset($_POST["GGGG"])?$_POST["GGGG"]:"";
$EGGG = isset($_POST["EGGG"])?$_POST["EGGG"]:"";
$OGGG = isset($_POST["OGGG"])?$_POST["OGGG"]:"";
$OBSERVACIONES = isset($_POST["OBSERVACIONES"])?$_POST["OBSERVACIONES"]:"";
$habilidades1 = isset($_POST["habilidades1"])?$_POST["habilidades1"]:""; 

	echo $conexion->guardar_habilidades(  $LUNES , $LHORARIOS , $LOBSERBACIONES , $MARTES , $MAHORARIOS , $MAOBSERBACIONES , $MIERCOLES , $MIHORARIOS , $MIOBSERBACIONES , $JUEVES , $JHORARIOS , $JOBSERBACIONES , $VIERNES , $VHORARIOS , $VOBSERBACIONES , $SABADO , $SHORARIOS , $SOBSERBACIONES , $DOMINGO , $DHORARIOS , $DOBSERBACIONES , $FIESTA_MEXICANA , $EFIESTA_MEXICANA , $OFIESTA_MEXICANA , $JEOPARDY , $EJEOPARDY , $OJEOPARDY , $RALLYS , $ERALLYS , $ORALLYS , $a100_MEXICANOS_DIJIERON , $E100_MEXICANOS_DIJIERON , $O100_MEXICANOS_DIJIERON , $NOCHE_DE_LAS_ESTRELLAS , $ENOCHE_DE_LAS_ESTRELLAS , $ONOCHE_DE_LAS_ESTRELLAS , $HANDS_UP , $EHANDS_UP , $OHANDS_UP , $CALAMAR , $ECALAMAR , $OCALAMAR , $CRUCERO , $ECRUCERO , $OCRUCERO , $MAESTRO_DE_CEREMONIAS , $EMAESTRO_DE_CEREMONIAS , $OMAESTRO_DE_CEREMONIAS , $CASINO , $ECASINO , $OCASINO , $CUBILETE , $ECUBILETE , $OCUBILETE , $CRABS , $ECRABS , $OCRABS , $RULETA , $ERULETA , $ORULETA , $BLACK_JACK , $EBLACK_JACK , $OBLACK_JACK , $INFLABLES , $EINFLABLES , $OINFLABLES , $AAA , $AAAA , $EAAAA , $OAAAA , $BBB , $BBBB , $EBBB , $OBBB , $CCC , $CCCC , $ECCC , $OCCC , $DDD , $EDDD , $ODDD , $EEE , $EEEEE , $EEEE , $OEEE , $FFF , $FFFF , $EFFF , $OFFF , $GGG , $GGGG , $EGGG , $OGGG , $OBSERVACIONES , $habilidades1  );

//include_once (__ROOT1__."/includes/crea_funciones.php");	
}
else{
	//echo "nada";
//include_once (__ROOT1__."/includes/crea_funciones.php");
}

foreach($_FILES AS $ETQIETA => $VALOR){
	echo $conexion->cargar($ETQIETA);
}


?>