<?php 


$ROWdatoscolaborador3a = $conexion->variableCOORDINADOR2();

$url = isset($ROWdatoscolaborador3a["url"])?$ROWdatoscolaborador3a["url"]:"";
$ESTATUS_CRM_ACTIVOBAJA = isset($ROWdatoscolaborador3a["ESTATUS_CRM_ACTIVOBAJA"])?$ROWdatoscolaborador3a["ESTATUS_CRM_ACTIVOBAJA"]:"";
$STATUS_CARGA_INFORMACION = isset($ROWdatoscolaborador3a["STATUS_CARGA_INFORMACION"])?$ROWdatoscolaborador3a["STATUS_CARGA_INFORMACION"]:"";
$DATOS_COLABORADORES = isset($ROWdatoscolaborador3a["DATOS_COLABORADORES"])?$ROWdatoscolaborador3a["DATOS_COLABORADORES"]:"";




$ROW = $conexion->variablesadjuntos();

$ROW2= array( 'c_COLABORADOR' =>'c_COLABORADOR', 'c_COORDINADOR' => 'c_COORDINADOR', 'c_ANIMADOR'=>'c_ANIMADOR','url'=>'url','ESTATUS'=>'ESTATUS','DATOS_COLABORADORES'=>'DATOS_COLABORADORES');
//print_r($ROW);
$datoscolaboradorporcentaje = $conexion->contadorporcentaje($ROW,$ROW2);

$F_ACTA_NACIMIENTO = isset($ROW["F_ACTA_NACIMIENTO"])?$ROW["F_ACTA_NACIMIENTO"]:"";
$F_COMPROBANTE_DOMICILIO = isset($ROW["F_COMPROBANTE_DOMICILIO"])?$ROW["F_COMPROBANTE_DOMICILIO"]:"";
$F_CONSTANCIA_SITUACION_FISCAL = isset($ROW["F_CONSTANCIA_SITUACION_FISCAL"])?$ROW["F_CONSTANCIA_SITUACION_FISCAL"]:"";
$F_RFC = isset($ROW["F_RFC"])?$ROW["F_RFC"]:"";
$F_CURP = isset($ROW["F_CURP"])?$ROW["F_CURP"]:"";
$F_ALTA_SEGURO_SOCIAL = isset($ROW["F_ALTA_SEGURO_SOCIAL"])?$ROW["F_ALTA_SEGURO_SOCIAL"]:"";
$F_ALTA_SEGURO_SOCIAL_EPC = isset($ROW["F_ALTA_SEGURO_SOCIAL_EPC"])?$ROW["F_ALTA_SEGURO_SOCIAL_EPC"]:"";
$F_INE_FRENTE = isset($ROW["F_INE_FRENTE"])?$ROW["F_INE_FRENTE"]:"";
$F_INE_REVERSO = isset($ROW["F_INE_REVERSO"])?$ROW["F_INE_REVERSO"]:"";
$F_FOTO_ESTADO_CUENTA_BANCARIO = isset($ROW["F_FOTO_ESTADO_CUENTA_BANCARIO"])?$ROW["F_FOTO_ESTADO_CUENTA_BANCARIO"]:"";
$F_DOCUMENTO_CREDITO_INFONAVIT = isset($ROW["F_DOCUMENTO_CREDITO_INFONAVIT"])?$ROW["F_DOCUMENTO_CREDITO_INFONAVIT"]:"";
$F_CARTA_DE_RECOMENDACION_1 = isset($ROW["F_CARTA_DE_RECOMENDACION_1"])?$ROW["F_CARTA_DE_RECOMENDACION_1"]:"";
$F_CARTA_DE_RECOMENDACION_2 = isset($ROW["F_CARTA_DE_RECOMENDACION_2"])?$ROW["F_CARTA_DE_RECOMENDACION_2"]:"";
$F_CARTA_DE_RECOMENDACION_3 = isset($ROW["F_CARTA_DE_RECOMENDACION_3"])?$ROW["F_CARTA_DE_RECOMENDACION_3"]:"";
$F_CONSTANCIA_DE_CURSOS = isset($ROW["F_CONSTANCIA_DE_CURSOS"])?$ROW["F_CONSTANCIA_DE_CURSOS"]:"";
$F_CONSTANCIA_ESTUDIOS = isset($ROW["F_CONSTANCIA_ESTUDIOS"])?$ROW["F_CONSTANCIA_ESTUDIOS"]:"";
$F_CERTIFICADO_VACUNA_1 = isset($ROW["F_CERTIFICADO_VACUNA_1"])?$ROW["F_CERTIFICADO_VACUNA_1"]:"";
$F_CERTIFICADO_VACUNA_2 = isset($ROW["F_CERTIFICADO_VACUNA_2"])?$ROW["F_CERTIFICADO_VACUNA_2"]:"";
$F_CERTIFICADO_VACUNA_3 = isset($ROW["F_CERTIFICADO_VACUNA_3"])?$ROW["F_CERTIFICADO_VACUNA_3"]:"";
$F_CERTIFICADO_VACUNA_4 = isset($ROW["F_CERTIFICADO_VACUNA_4"])?$ROW["F_CERTIFICADO_VACUNA_4"]:"";
$F_CURRICULUM_VITAE = isset($ROW["F_CURRICULUM_VITAE"])?$ROW["F_CURRICULUM_VITAE"]:"";
$F_LICENCIA_CONDUCIR = isset($ROW["F_LICENCIA_CONDUCIR"])?$ROW["F_LICENCIA_CONDUCIR"]:"";
$F_PASAPORTE = isset($ROW["F_PASAPORTE"])?$ROW["F_PASAPORTE"]:"";
$F_VISA_AMERICANA = isset($ROW["F_VISA_AMERICANA"])?$ROW["F_VISA_AMERICANA"]:"";
$F_LICENCIA_DE_CONDUCIR = isset($ROW["F_LICENCIA_DE_CONDUCIR"])?$ROW["F_LICENCIA_DE_CONDUCIR"]:"";
$F_FM3_EN_CASO_DE_SER_EXTRANJERO = isset($ROW["F_FM3_EN_CASO_DE_SER_EXTRANJERO"])?$ROW["F_FM3_EN_CASO_DE_SER_EXTRANJERO"]:"";
$F_CARTILLA_LIBERADA = isset($ROW["F_CARTILLA_LIBERADA"])?$ROW["F_CARTILLA_LIBERADA"]:"";
$F_FOTO_ACTUAL = isset($ROW["F_FOTO_ACTUAL"])?$ROW["F_FOTO_ACTUAL"]:"";
$F_CONTRATO_LABORAL_EPC_1 = isset($ROW["F_CONTRATO_LABORAL_EPC_1"])?$ROW["F_CONTRATO_LABORAL_EPC_1"]:"";
$F_CONTRATO_LABORAL_EPC_2 = isset($ROW["F_CONTRATO_LABORAL_EPC_2"])?$ROW["F_CONTRATO_LABORAL_EPC_2"]:"";
$F_CONTRATO_LABORAL_EPC_3 = isset($ROW["F_CONTRATO_LABORAL_EPC_3"])?$ROW["F_CONTRATO_LABORAL_EPC_3"]:"";
$F_CONTRATO_LABORAL_EPC_4 = isset($ROW["F_CONTRATO_LABORAL_EPC_4"])?$ROW["F_CONTRATO_LABORAL_EPC_4"]:"";
$F_CONTRATO_LABORAL_EPC_5 = isset($ROW["F_CONTRATO_LABORAL_EPC_5"])?$ROW["F_CONTRATO_LABORAL_EPC_5"]:"";
$F_CONTRATO_LABORAL_EPC_6 = isset($ROW["F_CONTRATO_LABORAL_EPC_6"])?$ROW["F_CONTRATO_LABORAL_EPC_6"]:"";
$F_CONTRATO_LABORAL_EPC_7 = isset($ROW["F_CONTRATO_LABORAL_EPC_7"])?$ROW["F_CONTRATO_LABORAL_EPC_7"]:"";
$F_CONTRATO_LABORAL_EPC_8 = isset($ROW["F_CONTRATO_LABORAL_EPC_8"])?$ROW["F_CONTRATO_LABORAL_EPC_8"]:"";
$F_CONTRATO_CONF_ENTRADA_EPC = isset($ROW["F_CONTRATO_CONF_ENTRADA_EPC"])?$ROW["F_CONTRATO_CONF_ENTRADA_EPC"]:"";
$F_REGLAMENTO_FIRMADO = isset($ROW["F_REGLAMENTO_FIRMADO"])?$ROW["F_REGLAMENTO_FIRMADO"]:"";
$F_CODIGO_CONDUCTA_FIRMADO = isset($ROW["F_CODIGO_CONDUCTA_FIRMADO"])?$ROW["F_CODIGO_CONDUCTA_FIRMADO"]:"";
$F_POLITICAS_EMPRESA_FIRMADO = isset($ROW["F_POLITICAS_EMPRESA_FIRMADO"])?$ROW["F_POLITICAS_EMPRESA_FIRMADO"]:"";
$F_CARTA_RENUNCIA_1 = isset($ROW["F_CARTA_RENUNCIA_1"])?$ROW["F_CARTA_RENUNCIA_1"]:"";
$F_CARTA_RENUNCIA_2 = isset($ROW["F_CARTA_RENUNCIA_2"])?$ROW["F_CARTA_RENUNCIA_2"]:"";
$F_CALCULO_FINIQUITO_1 = isset($ROW["F_CALCULO_FINIQUITO_1"])?$ROW["F_CALCULO_FINIQUITO_1"]:"";
$F_CALCULO_FINIQUITO_2 = isset($ROW["F_CALCULO_FINIQUITO_2"])?$ROW["F_CALCULO_FINIQUITO_2"]:"";
$F_CALCULO_FINIQUITO_3 = isset($ROW["F_CALCULO_FINIQUITO_3"])?$ROW["F_CALCULO_FINIQUITO_3"]:"";
$F_CONTRATO_CONF_SALIDA = isset($ROW["F_CONTRATO_CONF_SALIDA"])?$ROW["F_CONTRATO_CONF_SALIDA"]:"";
$F_DOCUMENTOS_LEGALES_1 = isset($ROW["F_DOCUMENTOS_LEGALES_1"])?$ROW["F_DOCUMENTOS_LEGALES_1"]:"";
$F_DOCUMENTOS_LEGALES_2 = isset($ROW["F_DOCUMENTOS_LEGALES_2"])?$ROW["F_DOCUMENTOS_LEGALES_2"]:"";
$F_DOCUMENTOS_LEGALES_3 = isset($ROW["F_DOCUMENTOS_LEGALES_3"])?$ROW["F_DOCUMENTOS_LEGALES_3"]:"";
$F_DOCUMENTOS_LEGALES_4 = isset($ROW["F_DOCUMENTOS_LEGALES_4"])?$ROW["F_DOCUMENTOS_LEGALES_4"]:"";
$F_OTROS_DOCUMENTOS_1 = isset($ROW["F_OTROS_DOCUMENTOS_1"])?$ROW["F_OTROS_DOCUMENTOS_1"]:"";
$F_OTROS_DOCUMENTOS_2 = isset($ROW["F_OTROS_DOCUMENTOS_2"])?$ROW["F_OTROS_DOCUMENTOS_2"]:"";
$F_OTROS_DOCUMENTOS_3 = isset($ROW["F_OTROS_DOCUMENTOS_3"])?$ROW["F_OTROS_DOCUMENTOS_3"]:"";
$F_OTROS_DOCUMENTOS_4 = isset($ROW["F_OTROS_DOCUMENTOS_4"])?$ROW["F_OTROS_DOCUMENTOS_4"]:""; 



/*empresa*/
$ROWempresa = $conexion->variablesempresa();

$ROWempresa11= array();
$empresaporcentaje = $conexion->contadorporcentaje($ROWempresa,$ROWempresa11);

$FECHA_INGRESO = isset($ROWempresa["FECHA_INGRESO"])?$ROWempresa["FECHA_INGRESO"]:"";
$NUMERO_COLABORADOR = isset($ROWempresa["NUMERO_COLABORADOR"])?$ROWempresa["NUMERO_COLABORADOR"]:"";
$NUMERO_REGISTRO_BIOMETRICO = isset($ROWempresa["NUMERO_REGISTRO_BIOMETRICO"])?$ROWempresa["NUMERO_REGISTRO_BIOMETRICO"]:"";
$CONTRASENIA_REGISTRO_BIOMETRICO = isset($ROWempresa["CONTRASENIA_REGISTRO_BIOMETRICO"])?$ROWempresa["CONTRASENIA_REGISTRO_BIOMETRICO"]:"";
$USUARIO_CRM = isset($ROWempresa["USUARIO_CRM"])?$ROWempresa["USUARIO_CRM"]:"";
$CONTRASENIA_CRM = isset($ROWempresa["CONTRASENIA_CRM"])?$ROWempresa["CONTRASENIA_CRM"]:"";
$NIVEL_ACCESO_CRM = isset($ROWempresa["NIVEL_ACCESO_CRM"])?$ROWempresa["NIVEL_ACCESO_CRM"]:"";
$PUESTO = isset($ROWempresa["PUESTO"])?$ROWempresa["PUESTO"]:"";
$DEPARTAMENTO = isset($ROWempresa["DEPARTAMENTO"])?$ROWempresa["DEPARTAMENTO"]:"";
$NUMERO_TARJETA_CREDITO = isset($ROWempresa["NUMERO_TARJETA_CREDITO"])?$ROWempresa["NUMERO_TARJETA_CREDITO"]:"";
$CORREO_1 = isset($ROWempresa["CORREO_1"])?$ROWempresa["CORREO_1"]:"";
$CORREO_2 = isset($ROWempresa["CORREO_2"])?$ROWempresa["CORREO_2"]:"";
$CORREO_3 = isset($ROWempresa["CORREO_3"])?$ROWempresa["CORREO_3"]:"";
$empresa = isset($ROWempresa["empresa"])?$ROWempresa["empresa"]:"";
$FECHA_SALIDA_EMPRESA = isset($ROWempresa["FECHA_SALIDA_EMPRESA"])?$ROWempresa["FECHA_SALIDA_EMPRESA"]:"";
$MOTIVO_SALIDA_EMPRESA = isset($ROWempresa["MOTIVO_SALIDA_EMPRESA"])?$ROWempresa["MOTIVO_SALIDA_EMPRESA"]:"";


/*informacion personal*/
$ROWipersonal = $conexion->variablesIPERSONAL();
$ROWempresa11= array();
$ROWipersonala1 = $conexion->contadorporcentaje($ROWipersonal,$ROWempresa11);
$NOMBRE_1 = isset($ROWipersonal["NOMBRE_1"])?$ROWipersonal["NOMBRE_1"]:"";
$NOMBRE_2 = isset($ROWipersonal["NOMBRE_2"])?$ROWipersonal["NOMBRE_2"]:"";
$NOMBRE_3 = isset($ROWipersonal["NOMBRE_3"])?$ROWipersonal["NOMBRE_3"]:"";
$APELLIDO_MATERNO = isset($ROWipersonal["APELLIDO_MATERNO"])?$ROWipersonal["APELLIDO_MATERNO"]:"";
$APELLIDO_PATERNO = isset($ROWipersonal["APELLIDO_PATERNO"])?$ROWipersonal["APELLIDO_PATERNO"]:"";

$IPCORREO1 = isset($ROWipersonal["IPCORREO1"])?$ROWipersonal["IPCORREO1"]:"";
$IPCORREO2 = isset($ROWipersonal["IPCORREO2"])?$ROWipersonal["IPCORREO2"]:"";


$FECHA_DE_NACIMIENTO = isset($ROWipersonal["FECHA_DE_NACIMIENTO"])?$ROWipersonal["FECHA_DE_NACIMIENTO"]:"";
$ANIOS = isset($ROWipersonal["ANIOS"])?$ROWipersonal["ANIOS"]:"";
$LUGAR_DE_NACIMIENTO_ESTADO_PROVINCIA = isset($ROWipersonal["LUGAR_DE_NACIMIENTO_ESTADO_PROVINCIA"])?$ROWipersonal["LUGAR_DE_NACIMIENTO_ESTADO_PROVINCIA"]:"";
$PAIS_DE_NACIMIENTO = isset($ROWipersonal["PAIS_DE_NACIMIENTO"])?$ROWipersonal["PAIS_DE_NACIMIENTO"]:"";
$ESTADO_CIVIL = isset($ROWipersonal["ESTADO_CIVIL"])?$ROWipersonal["ESTADO_CIVIL"]:"";
$NUMERO_DE_FAMILIARES_PADRES_HERMANOS = isset($ROWipersonal["NUMERO_DE_FAMILIARES_PADRES_HERMANOS"])?$ROWipersonal["NUMERO_DE_FAMILIARES_PADRES_HERMANOS"]:"";
$NUMERO_DE_FAMILIARES_ESPOSA_HIJOS = isset($ROWipersonal["NUMERO_DE_FAMILIARES_ESPOSA_HIJOS"])?$ROWipersonal["NUMERO_DE_FAMILIARES_ESPOSA_HIJOS"]:"";
$CELULAR_1 = isset($ROWipersonal["CELULAR_1"])?$ROWipersonal["CELULAR_1"]:"";
$CELULAR_2 = isset($ROWipersonal["CELULAR_2"])?$ROWipersonal["CELULAR_2"]:"";
$TELEFONO_DE_CASA_1 = isset($ROWipersonal["TELEFONO_DE_CASA_1"])?$ROWipersonal["TELEFONO_DE_CASA_1"]:"";
$TELEFONO_DE_CASA_2 = isset($ROWipersonal["TELEFONO_DE_CASA_2"])?$ROWipersonal["TELEFONO_DE_CASA_2"]:"";
$PORCENTAJE_DE_INGLES_HABLADO = isset($ROWipersonal["PORCENTAJE_DE_INGLES_HABLADO"])?$ROWipersonal["PORCENTAJE_DE_INGLES_HABLADO"]:"";
$PORCENTAJE_DE_INGLES_ESCRITO = isset($ROWipersonal["PORCENTAJE_DE_INGLES_ESCRITO"])?$ROWipersonal["PORCENTAJE_DE_INGLES_ESCRITO"]:"";
$DOMINIO_DE_OTRO_IDIOMA_Y_PORCENTAJE = isset($ROWipersonal["DOMINIO_DE_OTRO_IDIOMA_Y_PORCENTAJE"])?$ROWipersonal["DOMINIO_DE_OTRO_IDIOMA_Y_PORCENTAJE"]:"";
$BENEFICIARIO_Y_PORCENTAJE_1_PARA_SEGURO = isset($ROWipersonal["BENEFICIARIO_Y_PORCENTAJE_1_PARA_SEGURO"])?$ROWipersonal["BENEFICIARIO_Y_PORCENTAJE_1_PARA_SEGURO"]:"";
$BENEFICIARIO_Y_PORCENTAJE_2_PARA_SEGURO = isset($ROWipersonal["BENEFICIARIO_Y_PORCENTAJE_2_PARA_SEGURO"])?$ROWipersonal["BENEFICIARIO_Y_PORCENTAJE_2_PARA_SEGURO"]:"";
$BENEFICIARIO_YPORCENTAJE_3_PARA_SEGURO = isset($ROWipersonal["BENEFICIARIO_YPORCENTAJE_3_PARA_SEGURO"])?$ROWipersonal["BENEFICIARIO_YPORCENTAJE_3_PARA_SEGURO"]:"";
$TELEGRAM = isset($ROWipersonal["TELEGRAM"])?$ROWipersonal["TELEGRAM"]:"";
$TIPO_DE_SANGRE = isset($ROWipersonal["TIPO_DE_SANGRE"])?$ROWipersonal["TIPO_DE_SANGRE"]:"";
$AUTO = isset($ROWipersonal["AUTO"])?$ROWipersonal["AUTO"]:"";
$MARCA_DEL_AUTO = isset($ROWipersonal["MARCA_DEL_AUTO"])?$ROWipersonal["MARCA_DEL_AUTO"]:"";
$SUB_MARCA = isset($ROWipersonal["SUB_MARCA"])?$ROWipersonal["SUB_MARCA"]:"";
$MODELO = isset($ROWipersonal["MODELO"])?$ROWipersonal["MODELO"]:"";
$ipersonal1 = isset($ROWipersonal["ipersonal1"])?$ROWipersonal["ipersonal1"]:"";
$COLOR = isset($ROWipersonal["COLOR"])?$ROWipersonal["COLOR"]:"";
$PLACAS = isset($ROWipersonal["PLACAS"])?$ROWipersonal["PLACAS"]:""; 



/*DIR CASA 1*/
$ROWdircasa1 = $conexion->variablesdircasa1();

$ROW2= array( );
//print_r($ROW);
$datosROWdircasa1 = $conexion->contadorporcentaje($ROWdircasa1,$ROW2);

$EDIFICIO = isset($ROWdircasa1["EDIFICIO"])?$ROWdircasa1["EDIFICIO"]:"";
$calledir1 = isset($ROWdircasa1["calledir1"])?$ROWdircasa1["calledir1"]:"";
$NUMERO_EXTERIOR = isset($ROWdircasa1["NUMERO_EXTERIOR"])?$ROWdircasa1["NUMERO_EXTERIOR"]:"";
$NUMERO_INTERIOR = isset($ROWdircasa1["NUMERO_INTERIOR"])?$ROWdircasa1["NUMERO_INTERIOR"]:"";
$NUMERO_INTERIOR_2 = isset($ROWdircasa1["NUMERO_INTERIOR_2"])?$ROWdircasa1["NUMERO_INTERIOR_2"]:"";
$COLONIA = isset($ROWdircasa1["COLONIA"])?$ROWdircasa1["COLONIA"]:"";
$ALCALDIA = isset($ROWdircasa1["ALCALDIA"])?$ROWdircasa1["ALCALDIA"]:"";
$C_P = isset($ROWdircasa1["C_P"])?$ROWdircasa1["C_P"]:"";
$CIUDAD = isset($ROWdircasa1["CIUDAD"])?$ROWdircasa1["CIUDAD"]:"";
$ESTADO = isset($ROWdircasa1["ESTADO"])?$ROWdircasa1["ESTADO"]:"";
$PAIS = isset($ROWdircasa1["PAIS"])?$ROWdircasa1["PAIS"]:"";
$dircasa11 = isset($ROWdircasa1["dircasa11"])?$ROWdircasa1["dircasa11"]:"";
$DIRECCION_DE_CASA_1_UBICACION_MAPA = isset($ROWdircasa1["DIRECCION_DE_CASA_1_UBICACION_MAPA"])?$ROWdircasa1["DIRECCION_DE_CASA_1_UBICACION_MAPA"]:"";


/*DIR CASA 1*/
$ROWdircasa2 = $conexion->variablesdircasa2();
$ROW2= array( );
//print_r($ROW);
$datosROWdircasa2 = $conexion->contadorporcentaje($ROWdircasa2,$ROW2);

$DIRECCION_CASA_2_EDIFICIO = isset($ROWdircasa2["DIRECCION_CASA_2_EDIFICIO"])?$ROWdircasa2["DIRECCION_CASA_2_EDIFICIO"]:"";
$calledir2 = isset($ROWdircasa2["calledir2"])?$ROWdircasa2["calledir2"]:"";
$DIRECCION_CASA_2_NUMERO_EXTERIOR = isset($ROWdircasa2["DIRECCION_CASA_2_NUMERO_EXTERIOR"])?$ROWdircasa2["DIRECCION_CASA_2_NUMERO_EXTERIOR"]:"";
$DIRECCION_CASA_2_INTERIOR = isset($ROWdircasa2["DIRECCION_CASA_2_INTERIOR"])?$ROWdircasa2["DIRECCION_CASA_2_INTERIOR"]:"";
$DIRECCION_CASA_INTERIOR_2 = isset($ROWdircasa2["DIRECCION_CASA_INTERIOR_2"])?$ROWdircasa2["DIRECCION_CASA_INTERIOR_2"]:"";
$DIRECCION_CASA_2_COLONIA = isset($ROWdircasa2["DIRECCION_CASA_2_COLONIA"])?$ROWdircasa2["DIRECCION_CASA_2_COLONIA"]:"";
$DIRECCION_CASA_2_ALCALDIA = isset($ROWdircasa2["DIRECCION_CASA_2_ALCALDIA"])?$ROWdircasa2["DIRECCION_CASA_2_ALCALDIA"]:"";
$DIRECCION_CASA_2_C_P = isset($ROWdircasa2["DIRECCION_CASA_2_C_P"])?$ROWdircasa2["DIRECCION_CASA_2_C_P"]:"";
$DIRECCION_CASA_2_CIUDAD = isset($ROWdircasa2["DIRECCION_CASA_2_CIUDAD"])?$ROWdircasa2["DIRECCION_CASA_2_CIUDAD"]:"";
$DIRECCION_CASA_2_ESTADO = isset($ROWdircasa2["DIRECCION_CASA_2_ESTADO"])?$ROWdircasa2["DIRECCION_CASA_2_ESTADO"]:"";
$DIRECCION_CASA_2_PAIS = isset($ROWdircasa2["DIRECCION_CASA_2_PAIS"])?$ROWdircasa2["DIRECCION_CASA_2_PAIS"]:"";
$dircasa22 = isset($ROWdircasa2["dircasa22"])?$ROWdircasa2["dircasa22"]:"";
$DIRECCION_DE_CASA_2__UBICACION_EN_EL_MAPA = isset($ROWdircasa2["DIRECCION_DE_CASA_2__UBICACION_EN_EL_MAPA"])?$ROWdircasa2["DIRECCION_DE_CASA_2__UBICACION_EN_EL_MAPA"]:"";


/*DIR CASA 1*/
$ROWf1cercano = $conexion->variablesf1cercano();
$ROW2= array( );
//print_r($ROW);
$ROWf1cercano1a1 = $conexion->contadorporcentaje($ROWf1cercano,$ROW2);
$FAMILIAR_1_PARENTESCO = isset($ROWf1cercano["FAMILIAR_1_PARENTESCO"])?$ROWf1cercano["FAMILIAR_1_PARENTESCO"]:"";
$FAMILIAR_1_NOMBRE_1 = isset($ROWf1cercano["FAMILIAR_1_NOMBRE_1"])?$ROWf1cercano["FAMILIAR_1_NOMBRE_1"]:"";
$FAMILIAR_1_NOMBRE_2 = isset($ROWf1cercano["FAMILIAR_1_NOMBRE_2"])?$ROWf1cercano["FAMILIAR_1_NOMBRE_2"]:"";
$FAMILIAR_1_APELLIDO_MATERNO = isset($ROWf1cercano["FAMILIAR_1_APELLIDO_MATERNO"])?$ROWf1cercano["FAMILIAR_1_APELLIDO_MATERNO"]:"";
$FAMILIAR_1_APELLIDO_PATERNO = isset($ROWf1cercano["FAMILIAR_1_APELLIDO_PATERNO"])?$ROWf1cercano["FAMILIAR_1_APELLIDO_PATERNO"]:"";
$FAMILIAR_1_CELULAR_1 = isset($ROWf1cercano["FAMILIAR_1_CELULAR_1"])?$ROWf1cercano["FAMILIAR_1_CELULAR_1"]:"";
$FAMILIAR_1_CELULAR_2 = isset($ROWf1cercano["FAMILIAR_1_CELULAR_2"])?$ROWf1cercano["FAMILIAR_1_CELULAR_2"]:"";
$FAMILIAR_1_TELEFONO_DE_CASA_I = isset($ROWf1cercano["FAMILIAR_1_TELEFONO_DE_CASA_I"])?$ROWf1cercano["FAMILIAR_1_TELEFONO_DE_CASA_I"]:"";
$FAMILIAR_1_CORREO_ELECTRONICO = isset($ROWf1cercano["FAMILIAR_1_CORREO_ELECTRONICO"])?$ROWf1cercano["FAMILIAR_1_CORREO_ELECTRONICO"]:"";
$FAMILIAR_1_EDIFICIO = isset($ROWf1cercano["FAMILIAR_1_EDIFICIO"])?$ROWf1cercano["FAMILIAR_1_EDIFICIO"]:"";
$FAMILIAR_1_NUMERO_CALLE = isset($ROWf1cercano["FAMILIAR_1_NUMERO_CALLE"])?$ROWf1cercano["FAMILIAR_1_NUMERO_CALLE"]:"";
$FAMILIAR_1_NUMERO_EXTERIOR = isset($ROWf1cercano["FAMILIAR_1_NUMERO_EXTERIOR"])?$ROWf1cercano["FAMILIAR_1_NUMERO_EXTERIOR"]:"";
$FAMILIAR_1_NUMERO_INTERIOR = isset($ROWf1cercano["FAMILIAR_1_NUMERO_INTERIOR"])?$ROWf1cercano["FAMILIAR_1_NUMERO_INTERIOR"]:"";
$FAMILIAR_1_NUMER__INTERIOR_2 = isset($ROWf1cercano["FAMILIAR_1_NUMER__INTERIOR_2"])?$ROWf1cercano["FAMILIAR_1_NUMER__INTERIOR_2"]:"";
$FAMILIAR_1_COLONIA = isset($ROWf1cercano["FAMILIAR_1_COLONIA"])?$ROWf1cercano["FAMILIAR_1_COLONIA"]:"";
$FAMILIAR_1_ALCALDIA = isset($ROWf1cercano["FAMILIAR_1_ALCALDIA"])?$ROWf1cercano["FAMILIAR_1_ALCALDIA"]:"";
$FAMILIAR_1_C_P = isset($ROWf1cercano["FAMILIAR_1_C_P"])?$ROWf1cercano["FAMILIAR_1_C_P"]:"";
$FAMILIAR_1_CIUDAD = isset($ROWf1cercano["FAMILIAR_1_CIUDAD"])?$ROWf1cercano["FAMILIAR_1_CIUDAD"]:"";
$FAMILIAR_1_ESTADO = isset($ROWf1cercano["FAMILIAR_1_ESTADO"])?$ROWf1cercano["FAMILIAR_1_ESTADO"]:"";
$FAMILIAR_1_PAIS = isset($ROWf1cercano["FAMILIAR_1_PAIS"])?$ROWf1cercano["FAMILIAR_1_PAIS"]:"";
$F1CERCANO1 = isset($ROWf1cercano["F1CERCANO1"])?$ROWf1cercano["F1CERCANO1"]:"";
$FAMILIAR_1_UBICACION__EN_EL_MAPA = isset($ROWf1cercano["FAMILIAR_1_UBICACION__EN_EL_MAPA"])?$ROWf1cercano["FAMILIAR_1_UBICACION__EN_EL_MAPA"]:""; 


/*DIR CASA 2*/
$ROWf2cercano = $conexion->variablesf2cercano();
$ROW2= array( );
//print_r($ROW);
$ROWf2cercano1a1 = $conexion->contadorporcentaje($ROWf2cercano,$ROW2);
$FAMILIAR2_PARENTESCO = isset($ROWf2cercano["FAMILIAR2_PARENTESCO"])?$ROWf2cercano["FAMILIAR2_PARENTESCO"]:"";
$FAMILIAR2_NOMBRE_1 = isset($ROWf2cercano["FAMILIAR2_NOMBRE_1"])?$ROWf2cercano["FAMILIAR2_NOMBRE_1"]:"";
$FAMILIAR2_NOMBRE_2 = isset($ROWf2cercano["FAMILIAR2_NOMBRE_2"])?$ROWf2cercano["FAMILIAR2_NOMBRE_2"]:"";
$FAMILIAR2_APELLIDO_MATERNO = isset($ROWf2cercano["FAMILIAR2_APELLIDO_MATERNO"])?$ROWf2cercano["FAMILIAR2_APELLIDO_MATERNO"]:"";
$FAMILIAR2_APELLIDO_PATERNO = isset($ROWf2cercano["FAMILIAR2_APELLIDO_PATERNO"])?$ROWf2cercano["FAMILIAR2_APELLIDO_PATERNO"]:"";
$FAMILIAR2_CELULAR_1 = isset($ROWf2cercano["FAMILIAR2_CELULAR_1"])?$ROWf2cercano["FAMILIAR2_CELULAR_1"]:"";
$FAMILIAR2_CELULAR_2 = isset($ROWf2cercano["FAMILIAR2_CELULAR_2"])?$ROWf2cercano["FAMILIAR2_CELULAR_2"]:"";
$FAMILIAR2_TELEFONO_DE_CASA_I = isset($ROWf2cercano["FAMILIAR2_TELEFONO_DE_CASA_I"])?$ROWf2cercano["FAMILIAR2_TELEFONO_DE_CASA_I"]:"";
$FAMILIAR2_CORREO_ELECTRONICO = isset($ROWf2cercano["FAMILIAR2_CORREO_ELECTRONICO"])?$ROWf2cercano["FAMILIAR2_CORREO_ELECTRONICO"]:"";
$FAMILIAR2_EDIFICIO = isset($ROWf2cercano["FAMILIAR2_EDIFICIO"])?$ROWf2cercano["FAMILIAR2_EDIFICIO"]:"";
$FAMILIAR2_CALLE = isset($ROWf2cercano["FAMILIAR2_CALLE"])?$ROWf2cercano["FAMILIAR2_CALLE"]:"";
$FAMILIAR2_NUMERO_EXTERIOR = isset($ROWf2cercano["FAMILIAR2_NUMERO_EXTERIOR"])?$ROWf2cercano["FAMILIAR2_NUMERO_EXTERIOR"]:"";
$FAMILIAR2_NUMERO_INTERIOR = isset($ROWf2cercano["FAMILIAR2_NUMERO_INTERIOR"])?$ROWf2cercano["FAMILIAR2_NUMERO_INTERIOR"]:"";
$FAMILIAR2_NUMER_INTERIOR_2 = isset($ROWf2cercano["FAMILIAR2_NUMER_INTERIOR_2"])?$ROWf2cercano["FAMILIAR2_NUMER_INTERIOR_2"]:"";
$FAMILIAR2_COLONIA = isset($ROWf2cercano["FAMILIAR2_COLONIA"])?$ROWf2cercano["FAMILIAR2_COLONIA"]:"";
$FAMILIAR2_ALCALDIA = isset($ROWf2cercano["FAMILIAR2_ALCALDIA"])?$ROWf2cercano["FAMILIAR2_ALCALDIA"]:"";
$FAMILIAR2_C_P = isset($ROWf2cercano["FAMILIAR2_C_P"])?$ROWf2cercano["FAMILIAR2_C_P"]:"";
$FAMILIAR2_CIUDAD = isset($ROWf2cercano["FAMILIAR2_CIUDAD"])?$ROWf2cercano["FAMILIAR2_CIUDAD"]:"";
$FAMILIAR2_ESTADO = isset($ROWf2cercano["FAMILIAR2_ESTADO"])?$ROWf2cercano["FAMILIAR2_ESTADO"]:"";
$FAMILIAR2_PAIS = isset($ROWf2cercano["FAMILIAR2_PAIS"])?$ROWf2cercano["FAMILIAR2_PAIS"]:"";
$F2CERCANO2 = isset($ROWf2cercano["F2CERCANO2"])?$ROWf2cercano["F2CERCANO2"]:"";
$FAMILIAR2_UBICACION_EN_EL_MAPA = isset($ROWf2cercano["FAMILIAR2_UBICACION_EN_EL_MAPA"])?$ROWf2cercano["FAMILIAR2_UBICACION_EN_EL_MAPA"]:""; 


$ROWf3cercano = $conexion->variablesf3cercano();
$ROW2= array( );
//print_r($ROW);
$ROWf3cercano1a1 = $conexion->contadorporcentaje($ROWf3cercano,$ROW2);
$FAMILIAR3_PARENTESCO = isset($ROWf3cercano["FAMILIAR3_PARENTESCO"])?$ROWf3cercano["FAMILIAR3_PARENTESCO"]:"";
$FAMILIAR3_NOMBRE_1 = isset($ROWf3cercano["FAMILIAR3_NOMBRE_1"])?$ROWf3cercano["FAMILIAR3_NOMBRE_1"]:"";
$FAMILIAR3_NOMBRE_2 = isset($ROWf3cercano["FAMILIAR3_NOMBRE_2"])?$ROWf3cercano["FAMILIAR3_NOMBRE_2"]:"";
$FAMILIAR3_APELLIDO_MATERNO = isset($ROWf3cercano["FAMILIAR3_APELLIDO_MATERNO"])?$ROWf3cercano["FAMILIAR3_APELLIDO_MATERNO"]:"";
$FAMILIAR3_APELLIDO_PATERNO = isset($ROWf3cercano["FAMILIAR3_APELLIDO_PATERNO"])?$ROWf3cercano["FAMILIAR3_APELLIDO_PATERNO"]:"";
$FAMILIAR3_CELULAR_1 = isset($ROWf3cercano["FAMILIAR3_CELULAR_1"])?$ROWf3cercano["FAMILIAR3_CELULAR_1"]:"";
$FAMILIAR3_CELULAR_2 = isset($ROWf3cercano["FAMILIAR3_CELULAR_2"])?$ROWf3cercano["FAMILIAR3_CELULAR_2"]:"";
$FAMILIAR3_TELEFONO_DE_CASA_I = isset($ROWf3cercano["FAMILIAR3_TELEFONO_DE_CASA_I"])?$ROWf3cercano["FAMILIAR3_TELEFONO_DE_CASA_I"]:"";
$FAMILIAR3_CORREO_ELECTRONICO = isset($ROWf3cercano["FAMILIAR3_CORREO_ELECTRONICO"])?$ROWf3cercano["FAMILIAR3_CORREO_ELECTRONICO"]:"";
$FAMILIAR3_EDIFICIO = isset($ROWf3cercano["FAMILIAR3_EDIFICIO"])?$ROWf3cercano["FAMILIAR3_EDIFICIO"]:"";
$FAMILIAR3_calle = isset($ROWf3cercano["FAMILIAR3_calle"])?$ROWf3cercano["FAMILIAR3_calle"]:"";
$FAMILIAR3_NUMERO_EXTERIOR = isset($ROWf3cercano["FAMILIAR3_NUMERO_EXTERIOR"])?$ROWf3cercano["FAMILIAR3_NUMERO_EXTERIOR"]:"";
$FAMILIAR3_NUMERO_INTERIOR = isset($ROWf3cercano["FAMILIAR3_NUMERO_INTERIOR"])?$ROWf3cercano["FAMILIAR3_NUMERO_INTERIOR"]:"";
$FAMILIAR3_NUMER_INTERIOR_2 = isset($ROWf3cercano["FAMILIAR3_NUMER_INTERIOR_2"])?$ROWf3cercano["FAMILIAR3_NUMER_INTERIOR_2"]:"";
$FAMILIAR3_COLONIA = isset($ROWf3cercano["FAMILIAR3_COLONIA"])?$ROWf3cercano["FAMILIAR3_COLONIA"]:"";
$FAMILIAR3_ALCALDIA = isset($ROWf3cercano["FAMILIAR3_ALCALDIA"])?$ROWf3cercano["FAMILIAR3_ALCALDIA"]:"";
$FAMILIAR3_C_P = isset($ROWf3cercano["FAMILIAR3_C_P"])?$ROWf3cercano["FAMILIAR3_C_P"]:"";
$FAMILIAR3_CIUDAD = isset($ROWf3cercano["FAMILIAR3_CIUDAD"])?$ROWf3cercano["FAMILIAR3_CIUDAD"]:"";
$FAMILIAR3_ESTADO = isset($ROWf3cercano["FAMILIAR3_ESTADO"])?$ROWf3cercano["FAMILIAR3_ESTADO"]:"";
$FAMILIAR3_PAIS = isset($ROWf3cercano["FAMILIAR3_PAIS"])?$ROWf3cercano["FAMILIAR3_PAIS"]:"";
$F3CERCANO3 = isset($ROWf3cercano["F3CERCANO3"])?$ROWf3cercano["F3CERCANO3"]:"";
$FAMILIAR3_UBICACION_EN_EL_MAPA = isset($ROWf3cercano["FAMILIAR3_UBICACION_EN_EL_MAPA"])?$ROWf3cercano["FAMILIAR3_UBICACION_EN_EL_MAPA"]:"";


$ROWf4cercano = $conexion->variablesf4cercano();
$ROW2= array( );
//print_r($ROW);
$ROWf4cercano1a1 = $conexion->contadorporcentaje($ROWf4cercano,$ROW2);
$FAMILIAR4_PARENTESCO = isset($ROWf4cercano["FAMILIAR4_PARENTESCO"])?$ROWf4cercano["FAMILIAR4_PARENTESCO"]:"";
$FAMILIAR4_NOMBRE_1 = isset($ROWf4cercano["FAMILIAR4_NOMBRE_1"])?$ROWf4cercano["FAMILIAR4_NOMBRE_1"]:"";
$FAMILIAR4_NOMBRE_2 = isset($ROWf4cercano["FAMILIAR4_NOMBRE_2"])?$ROWf4cercano["FAMILIAR4_NOMBRE_2"]:"";
$FAMILIAR4_APELLIDO_MATERNO = isset($ROWf4cercano["FAMILIAR4_APELLIDO_MATERNO"])?$ROWf4cercano["FAMILIAR4_APELLIDO_MATERNO"]:"";
$FAMILIAR4_APELLIDO_PATERNO = isset($ROWf4cercano["FAMILIAR4_APELLIDO_PATERNO"])?$ROWf4cercano["FAMILIAR4_APELLIDO_PATERNO"]:"";
$FAMILIAR4_CELULAR_1 = isset($ROWf4cercano["FAMILIAR4_CELULAR_1"])?$ROWf4cercano["FAMILIAR4_CELULAR_1"]:"";
$FAMILIAR4_CELULAR_2 = isset($ROWf4cercano["FAMILIAR4_CELULAR_2"])?$ROWf4cercano["FAMILIAR4_CELULAR_2"]:"";
$FAMILIAR4_TELEFONO_DE_CASA_I = isset($ROWf4cercano["FAMILIAR4_TELEFONO_DE_CASA_I"])?$ROWf4cercano["FAMILIAR4_TELEFONO_DE_CASA_I"]:"";
$FAMILIAR4_CORREO_ELECTRONICO = isset($ROWf4cercano["FAMILIAR4_CORREO_ELECTRONICO"])?$ROWf4cercano["FAMILIAR4_CORREO_ELECTRONICO"]:"";
$FAMILIAR4_EDIFICIO = isset($ROWf4cercano["FAMILIAR4_EDIFICIO"])?$ROWf4cercano["FAMILIAR4_EDIFICIO"]:"";
$FAMILIAR4_CALLE = isset($ROWf4cercano["FAMILIAR4_CALLE"])?$ROWf4cercano["FAMILIAR4_CALLE"]:"";
$FAMILIAR4_NUMERO_EXTERIOR = isset($ROWf4cercano["FAMILIAR4_NUMERO_EXTERIOR"])?$ROWf4cercano["FAMILIAR4_NUMERO_EXTERIOR"]:"";
$FAMILIAR4_NUMERO_INTERIOR = isset($ROWf4cercano["FAMILIAR4_NUMERO_INTERIOR"])?$ROWf4cercano["FAMILIAR4_NUMERO_INTERIOR"]:"";
$FAMILIAR4_NUMER__INTERIOR_2 = isset($ROWf4cercano["FAMILIAR4_NUMER__INTERIOR_2"])?$ROWf4cercano["FAMILIAR4_NUMER__INTERIOR_2"]:"";
$FAMILIAR4_COLONIA = isset($ROWf4cercano["FAMILIAR4_COLONIA"])?$ROWf4cercano["FAMILIAR4_COLONIA"]:"";
$FAMILIAR4_ALCALDIA = isset($ROWf4cercano["FAMILIAR4_ALCALDIA"])?$ROWf4cercano["FAMILIAR4_ALCALDIA"]:"";
$FAMILIAR4_C_P = isset($ROWf4cercano["FAMILIAR4_C_P"])?$ROWf4cercano["FAMILIAR4_C_P"]:"";
$FAMILIAR4_CIUDAD = isset($ROWf4cercano["FAMILIAR4_CIUDAD"])?$ROWf4cercano["FAMILIAR4_CIUDAD"]:"";
$FAMILIAR4_ESTADO = isset($ROWf4cercano["FAMILIAR4_ESTADO"])?$ROWf4cercano["FAMILIAR4_ESTADO"]:"";
$FAMILIAR4_PAIS = isset($ROWf4cercano["FAMILIAR4_PAIS"])?$ROWf4cercano["FAMILIAR4_PAIS"]:"";
$F4CERCANO4 = isset($ROWf4cercano["F4CERCANO4"])?$ROWf4cercano["F4CERCANO4"]:"";
$FAMILIAR4_UBICACION_EN_EL_MAPA = isset($ROWf4cercano["FAMILIAR4_UBICACION_EN_EL_MAPA"])?$ROWf4cercano["FAMILIAR4_UBICACION_EN_EL_MAPA"]:""; 



$ROWhabilidades = $conexion->variableshabilidades();
$ROW2= array( );
//print_r($ROW);
$ROWfhabilidades1a1 = $conexion->contadorporcentaje($ROWhabilidades,$ROW2);
$LUNES = isset($ROWhabilidades["LUNES"])?$ROWhabilidades["LUNES"]:"";
$LHORARIOS = isset($ROWhabilidades["LHORARIOS"])?$ROWhabilidades["LHORARIOS"]:"";
$LOBSERBACIONES = isset($ROWhabilidades["LOBSERBACIONES"])?$ROWhabilidades["LOBSERBACIONES"]:"";
$MARTES = isset($ROWhabilidades["MARTES"])?$ROWhabilidades["MARTES"]:"";
$MAHORARIOS = isset($ROWhabilidades["MAHORARIOS"])?$ROWhabilidades["MAHORARIOS"]:"";
$MAOBSERBACIONES = isset($ROWhabilidades["MAOBSERBACIONES"])?$ROWhabilidades["MAOBSERBACIONES"]:"";
$MIERCOLES = isset($ROWhabilidades["MIERCOLES"])?$ROWhabilidades["MIERCOLES"]:"";
$MIHORARIOS = isset($ROWhabilidades["MIHORARIOS"])?$ROWhabilidades["MIHORARIOS"]:"";
$MIOBSERBACIONES = isset($ROWhabilidades["MIOBSERBACIONES"])?$ROWhabilidades["MIOBSERBACIONES"]:"";
$JUEVES = isset($ROWhabilidades["JUEVES"])?$ROWhabilidades["JUEVES"]:"";
$JHORARIOS = isset($ROWhabilidades["JHORARIOS"])?$ROWhabilidades["JHORARIOS"]:"";
$JOBSERBACIONES = isset($ROWhabilidades["JOBSERBACIONES"])?$ROWhabilidades["JOBSERBACIONES"]:"";
$VIERNES = isset($ROWhabilidades["VIERNES"])?$ROWhabilidades["VIERNES"]:"";
$VHORARIOS = isset($ROWhabilidades["VHORARIOS"])?$ROWhabilidades["VHORARIOS"]:"";
$VOBSERBACIONES = isset($ROWhabilidades["VOBSERBACIONES"])?$ROWhabilidades["VOBSERBACIONES"]:"";
$SABADO = isset($ROWhabilidades["SABADO"])?$ROWhabilidades["SABADO"]:"";
$SHORARIOS = isset($ROWhabilidades["SHORARIOS"])?$ROWhabilidades["SHORARIOS"]:"";
$SOBSERBACIONES = isset($ROWhabilidades["SOBSERBACIONES"])?$ROWhabilidades["SOBSERBACIONES"]:"";
$DOMINGO = isset($ROWhabilidades["DOMINGO"])?$ROWhabilidades["DOMINGO"]:"";
$DHORARIOS = isset($ROWhabilidades["DHORARIOS"])?$ROWhabilidades["DHORARIOS"]:"";
$DOBSERBACIONES = isset($ROWhabilidades["DOBSERBACIONES"])?$ROWhabilidades["DOBSERBACIONES"]:"";
$FIESTA_MEXICANA = isset($ROWhabilidades["FIESTA_MEXICANA"])?$ROWhabilidades["FIESTA_MEXICANA"]:"";
$EFIESTA_MEXICANA = isset($ROWhabilidades["EFIESTA_MEXICANA"])?$ROWhabilidades["EFIESTA_MEXICANA"]:"";
$OFIESTA_MEXICANA = isset($ROWhabilidades["OFIESTA_MEXICANA"])?$ROWhabilidades["OFIESTA_MEXICANA"]:"";
$JEOPARDY = isset($ROWhabilidades["JEOPARDY"])?$ROWhabilidades["JEOPARDY"]:"";
$EJEOPARDY = isset($ROWhabilidades["EJEOPARDY"])?$ROWhabilidades["EJEOPARDY"]:"";
$OJEOPARDY = isset($ROWhabilidades["OJEOPARDY"])?$ROWhabilidades["OJEOPARDY"]:"";
$RALLYS = isset($ROWhabilidades["RALLYS"])?$ROWhabilidades["RALLYS"]:"";
$ERALLYS = isset($ROWhabilidades["ERALLYS"])?$ROWhabilidades["ERALLYS"]:"";
$ORALLYS = isset($ROWhabilidades["ORALLYS"])?$ROWhabilidades["ORALLYS"]:"";
$a100_MEXICANOS_DIJIERON = isset($ROWhabilidades["a100_MEXICANOS_DIJIERON"])?$ROWhabilidades["a100_MEXICANOS_DIJIERON"]:"";
$E100_MEXICANOS_DIJIERON = isset($ROWhabilidades["E100_MEXICANOS_DIJIERON"])?$ROWhabilidades["E100_MEXICANOS_DIJIERON"]:"";
$O100_MEXICANOS_DIJIERON = isset($ROWhabilidades["O100_MEXICANOS_DIJIERON"])?$ROWhabilidades["O100_MEXICANOS_DIJIERON"]:"";
$NOCHE_DE_LAS_ESTRELLAS = isset($ROWhabilidades["NOCHE_DE_LAS_ESTRELLAS"])?$ROWhabilidades["NOCHE_DE_LAS_ESTRELLAS"]:"";
$ENOCHE_DE_LAS_ESTRELLAS = isset($ROWhabilidades["ENOCHE_DE_LAS_ESTRELLAS"])?$ROWhabilidades["ENOCHE_DE_LAS_ESTRELLAS"]:"";
$ONOCHE_DE_LAS_ESTRELLAS = isset($ROWhabilidades["ONOCHE_DE_LAS_ESTRELLAS"])?$ROWhabilidades["ONOCHE_DE_LAS_ESTRELLAS"]:"";
$HANDS_UP = isset($ROWhabilidades["HANDS_UP"])?$ROWhabilidades["HANDS_UP"]:"";
$EHANDS_UP = isset($ROWhabilidades["EHANDS_UP"])?$ROWhabilidades["EHANDS_UP"]:"";
$OHANDS_UP = isset($ROWhabilidades["OHANDS_UP"])?$ROWhabilidades["OHANDS_UP"]:"";
$CALAMAR = isset($ROWhabilidades["CALAMAR"])?$ROWhabilidades["CALAMAR"]:"";
$ECALAMAR = isset($ROWhabilidades["ECALAMAR"])?$ROWhabilidades["ECALAMAR"]:"";
$OCALAMAR = isset($ROWhabilidades["OCALAMAR"])?$ROWhabilidades["OCALAMAR"]:"";
$CRUCERO = isset($ROWhabilidades["CRUCERO"])?$ROWhabilidades["CRUCERO"]:"";
$ECRUCERO = isset($ROWhabilidades["ECRUCERO"])?$ROWhabilidades["ECRUCERO"]:"";
$OCRUCERO = isset($ROWhabilidades["OCRUCERO"])?$ROWhabilidades["OCRUCERO"]:"";
$MAESTRO_DE_CEREMONIAS = isset($ROWhabilidades["MAESTRO_DE_CEREMONIAS"])?$ROWhabilidades["MAESTRO_DE_CEREMONIAS"]:"";
$EMAESTRO_DE_CEREMONIAS = isset($ROWhabilidades["EMAESTRO_DE_CEREMONIAS"])?$ROWhabilidades["EMAESTRO_DE_CEREMONIAS"]:"";
$OMAESTRO_DE_CEREMONIAS = isset($ROWhabilidades["OMAESTRO_DE_CEREMONIAS"])?$ROWhabilidades["OMAESTRO_DE_CEREMONIAS"]:"";
$CASINO = isset($ROWhabilidades["CASINO"])?$ROWhabilidades["CASINO"]:"";
$ECASINO = isset($ROWhabilidades["ECASINO"])?$ROWhabilidades["ECASINO"]:"";
$OCASINO = isset($ROWhabilidades["OCASINO"])?$ROWhabilidades["OCASINO"]:"";
$CUBILETE = isset($ROWhabilidades["CUBILETE"])?$ROWhabilidades["CUBILETE"]:"";
$ECUBILETE = isset($ROWhabilidades["ECUBILETE"])?$ROWhabilidades["ECUBILETE"]:"";
$OCUBILETE = isset($ROWhabilidades["OCUBILETE"])?$ROWhabilidades["OCUBILETE"]:"";
$CRABS = isset($ROWhabilidades["CRABS"])?$ROWhabilidades["CRABS"]:"";
$ECRABS = isset($ROWhabilidades["ECRABS"])?$ROWhabilidades["ECRABS"]:"";
$OCRABS = isset($ROWhabilidades["OCRABS"])?$ROWhabilidades["OCRABS"]:"";
$RULETA = isset($ROWhabilidades["RULETA"])?$ROWhabilidades["RULETA"]:"";
$ERULETA = isset($ROWhabilidades["ERULETA"])?$ROWhabilidades["ERULETA"]:"";
$ORULETA = isset($ROWhabilidades["ORULETA"])?$ROWhabilidades["ORULETA"]:"";
$BLACK_JACK = isset($ROWhabilidades["BLACK_JACK"])?$ROWhabilidades["BLACK_JACK"]:"";
$EBLACK_JACK = isset($ROWhabilidades["EBLACK_JACK"])?$ROWhabilidades["EBLACK_JACK"]:"";
$OBLACK_JACK = isset($ROWhabilidades["OBLACK_JACK"])?$ROWhabilidades["OBLACK_JACK"]:"";
$INFLABLES = isset($ROWhabilidades["INFLABLES"])?$ROWhabilidades["INFLABLES"]:"";
$EINFLABLES = isset($ROWhabilidades["EINFLABLES"])?$ROWhabilidades["EINFLABLES"]:"";
$OINFLABLES = isset($ROWhabilidades["OINFLABLES"])?$ROWhabilidades["OINFLABLES"]:"";
$AAA = isset($ROWhabilidades["AAA"])?$ROWhabilidades["AAA"]:"";
$AAAA = isset($ROWhabilidades["AAAA"])?$ROWhabilidades["AAAA"]:"";
$EAAAA = isset($ROWhabilidades["EAAAA"])?$ROWhabilidades["EAAAA"]:"";
$OAAAA = isset($ROWhabilidades["OAAAA"])?$ROWhabilidades["OAAAA"]:"";
$BBB = isset($ROWhabilidades["BBB"])?$ROWhabilidades["BBB"]:"";
$BBBB = isset($ROWhabilidades["BBBB"])?$ROWhabilidades["BBBB"]:"";
$EBBB = isset($ROWhabilidades["EBBB"])?$ROWhabilidades["EBBB"]:"";
$OBBB = isset($ROWhabilidades["OBBB"])?$ROWhabilidades["OBBB"]:"";
$CCC = isset($ROWhabilidades["CCC"])?$ROWhabilidades["CCC"]:"";
$CCCC = isset($ROWhabilidades["CCCC"])?$ROWhabilidades["CCCC"]:"";
$ECCC = isset($ROWhabilidades["ECCC"])?$ROWhabilidades["ECCC"]:"";
$OCCC = isset($ROWhabilidades["OCCC"])?$ROWhabilidades["OCCC"]:"";
$DDD = isset($ROWhabilidades["DDD"])?$ROWhabilidades["DDD"]:"";
$DDDD = isset($ROWhabilidades["DDDD"])?$ROWhabilidades["DDDD"]:"";

$EDDD = isset($ROWhabilidades["EDDD"])?$ROWhabilidades["EDDD"]:"";
$ODDD = isset($ROWhabilidades["ODDD"])?$ROWhabilidades["ODDD"]:"";
$EEE = isset($ROWhabilidades["EEE"])?$ROWhabilidades["EEE"]:"";
$EEEEE = isset($ROWhabilidades["EEEEE"])?$ROWhabilidades["EEEEE"]:"";
$EEEE = isset($ROWhabilidades["EEEE"])?$ROWhabilidades["EEEE"]:"";
$OEEE = isset($ROWhabilidades["OEEE"])?$ROWhabilidades["OEEE"]:"";
$FFF = isset($ROWhabilidades["FFF"])?$ROWhabilidades["FFF"]:"";
$FFFF = isset($ROWhabilidades["FFFF"])?$ROWhabilidades["FFFF"]:"";
$EFFF = isset($ROWhabilidades["EFFF"])?$ROWhabilidades["EFFF"]:"";
$OFFF = isset($ROWhabilidades["OFFF"])?$ROWhabilidades["OFFF"]:"";
$GGG = isset($ROWhabilidades["GGG"])?$ROWhabilidades["GGG"]:"";
$GGGG = isset($ROWhabilidades["GGGG"])?$ROWhabilidades["GGGG"]:"";
$EGGG = isset($ROWhabilidades["EGGG"])?$ROWhabilidades["EGGG"]:"";
$OGGG = isset($ROWhabilidades["OGGG"])?$ROWhabilidades["OGGG"]:"";
$OBSERVACIONES = isset($ROWhabilidades["OBSERVACIONES"])?$ROWhabilidades["OBSERVACIONES"]:"";
$habilidades1 = isset($ROWhabilidades["habilidades1"])?$ROWhabilidades["habilidades1"]:"";


$ROWmeasignado1 = $conexion->variablesMEASIGNADO1();
$ROW2= array( );
//print_r($ROW);
$ROWfmeasignado1a1 = $conexion->contadorporcentaje($ROWmeasignado1,$ROW2);
$COMPUTADORA_MARCA = isset($ROWmeasignado1["COMPUTADORA_MARCA"])?$ROWmeasignado1["COMPUTADORA_MARCA"]:"";
$COMPUTADORA_NO_DE_CEL = isset($ROWmeasignado1["COMPUTADORA_NO_DE_CEL"])?$ROWmeasignado1["COMPUTADORA_NO_DE_CEL"]:"";
$COMPUTADORA_MODELO = isset($ROWmeasignado1["COMPUTADORA_MODELO"])?$ROWmeasignado1["COMPUTADORA_MODELO"]:"";
$COMPUTADORA_MODELO_2 = isset($ROWmeasignado1["COMPUTADORA_MODELO_2"])?$ROWmeasignado1["COMPUTADORA_MODELO_2"]:"";
$COMPUTADORA_NUMERO_DE_SERIE = isset($ROWmeasignado1["COMPUTADORA_NUMERO_DE_SERIE"])?$ROWmeasignado1["COMPUTADORA_NUMERO_DE_SERIE"]:"";
$PANTALLA_MARCA = isset($ROWmeasignado1["PANTALLA_MARCA"])?$ROWmeasignado1["PANTALLA_MARCA"]:"";
$PANTALLA_NO_DE_CEL = isset($ROWmeasignado1["PANTALLA_NO_DE_CEL"])?$ROWmeasignado1["PANTALLA_NO_DE_CEL"]:"";
$PANTALLA_MODELO = isset($ROWmeasignado1["PANTALLA_MODELO"])?$ROWmeasignado1["PANTALLA_MODELO"]:"";
$PANTALLA_MODELO_2 = isset($ROWmeasignado1["PANTALLA_MODELO_2"])?$ROWmeasignado1["PANTALLA_MODELO_2"]:"";
$PANTALLA_NUMERO_DE_SERIE = isset($ROWmeasignado1["PANTALLA_NUMERO_DE_SERIE"])?$ROWmeasignado1["PANTALLA_NUMERO_DE_SERIE"]:"";
$MOUSE_MARCA = isset($ROWmeasignado1["MOUSE_MARCA"])?$ROWmeasignado1["MOUSE_MARCA"]:"";
$MOUSE_NO_DE_CEL = isset($ROWmeasignado1["MOUSE_NO_DE_CEL"])?$ROWmeasignado1["MOUSE_NO_DE_CEL"]:"";
$MOUSE_MODELO = isset($ROWmeasignado1["MOUSE_MODELO"])?$ROWmeasignado1["MOUSE_MODELO"]:"";
$MOUSE_MODELO_2 = isset($ROWmeasignado1["MOUSE_MODELO_2"])?$ROWmeasignado1["MOUSE_MODELO_2"]:"";
$MOUSE_NUMERO_DE_SERIE = isset($ROWmeasignado1["MOUSE_NUMERO_DE_SERIE"])?$ROWmeasignado1["MOUSE_NUMERO_DE_SERIE"]:"";
$DISCO_EXTERNO_MARCA = isset($ROWmeasignado1["DISCO_EXTERNO_MARCA"])?$ROWmeasignado1["DISCO_EXTERNO_MARCA"]:"";
$DISCO_EXTERNO_NO_DE_CEL = isset($ROWmeasignado1["DISCO_EXTERNO_NO_DE_CEL"])?$ROWmeasignado1["DISCO_EXTERNO_NO_DE_CEL"]:"";
$DISCO_EXTERNO_MODELO = isset($ROWmeasignado1["DISCO_EXTERNO_MODELO"])?$ROWmeasignado1["DISCO_EXTERNO_MODELO"]:"";
$DISCO_EXTERNO_MODELO_2 = isset($ROWmeasignado1["DISCO_EXTERNO_MODELO_2"])?$ROWmeasignado1["DISCO_EXTERNO_MODELO_2"]:"";
$DISCO_EXTERNO_NUMERO_DE_SERIE = isset($ROWmeasignado1["DISCO_EXTERNO_NUMERO_DE_SERIE"])?$ROWmeasignado1["DISCO_EXTERNO_NUMERO_DE_SERIE"]:"";
$MATERIAL_EQUIPO_ASIGNADO_OTRO_MARCA = isset($ROWmeasignado1["MATERIAL_EQUIPO_ASIGNADO_OTRO_MARCA"])?$ROWmeasignado1["MATERIAL_EQUIPO_ASIGNADO_OTRO_MARCA"]:"";
$MATERIAL_EQUIPO_ASIGNADO_OTRO_NO_DE_CEL = isset($ROWmeasignado1["MATERIAL_EQUIPO_ASIGNADO_OTRO_NO_DE_CEL"])?$ROWmeasignado1["MATERIAL_EQUIPO_ASIGNADO_OTRO_NO_DE_CEL"]:"";
$MATERIAL_EQUIPO_ASIGNADO_OTRO_MODELO = isset($ROWmeasignado1["MATERIAL_EQUIPO_ASIGNADO_OTRO_MODELO"])?$ROWmeasignado1["MATERIAL_EQUIPO_ASIGNADO_OTRO_MODELO"]:"";
$MATERIAL_EQUIPO_ASIGNADO_OTRO_MODELO_2 = isset($ROWmeasignado1["MATERIAL_EQUIPO_ASIGNADO_OTRO_MODELO_2"])?$ROWmeasignado1["MATERIAL_EQUIPO_ASIGNADO_OTRO_MODELO_2"]:"";
$MATERIAL_EQUIPO_ASIGNADO_OTRO_NUMERO_DE_SERIE = isset($ROWmeasignado1["MATERIAL_EQUIPO_ASIGNADO_OTRO_NUMERO_DE_SERIE"])?$ROWmeasignado1["MATERIAL_EQUIPO_ASIGNADO_OTRO_NUMERO_DE_SERIE"]:"";
$MATERIAL_EQUIPO_ASIGNADO_OTRO_2_MARCA = isset($ROWmeasignado1["MATERIAL_EQUIPO_ASIGNADO_OTRO_2_MARCA"])?$ROWmeasignado1["MATERIAL_EQUIPO_ASIGNADO_OTRO_2_MARCA"]:"";
$MATERIAL_EQUIPO_ASIGNADO_OTRO_2_NO_DE_CEL = isset($ROWmeasignado1["MATERIAL_EQUIPO_ASIGNADO_OTRO_2_NO_DE_CEL"])?$ROWmeasignado1["MATERIAL_EQUIPO_ASIGNADO_OTRO_2_NO_DE_CEL"]:"";
$MATERIAL_EQUIPO_ASIGNADO_OTRO_2_MODELO = isset($ROWmeasignado1["MATERIAL_EQUIPO_ASIGNADO_OTRO_2_MODELO"])?$ROWmeasignado1["MATERIAL_EQUIPO_ASIGNADO_OTRO_2_MODELO"]:"";
$MATERIAL_EQUIPO_ASIGNADO_OTRO_2_MODELO_2 = isset($ROWmeasignado1["MATERIAL_EQUIPO_ASIGNADO_OTRO_2_MODELO_2"])?$ROWmeasignado1["MATERIAL_EQUIPO_ASIGNADO_OTRO_2_MODELO_2"]:"";
$MATERIAL_EQUIPO_ASIGNADO_OTRO_2_NUMERO_DE_SERIE = isset($ROWmeasignado1["MATERIAL_EQUIPO_ASIGNADO_OTRO_2_NUMERO_DE_SERIE"])?$ROWmeasignado1["MATERIAL_EQUIPO_ASIGNADO_OTRO_2_NUMERO_DE_SERIE"]:"";
$TELEFONO_CELULAR_MARCA = isset($ROWmeasignado1["TELEFONO_CELULAR_MARCA"])?$ROWmeasignado1["TELEFONO_CELULAR_MARCA"]:"";
$TELEFONO_CELULAR_NO_DE_CEL = isset($ROWmeasignado1["TELEFONO_CELULAR_NO_DE_CEL"])?$ROWmeasignado1["TELEFONO_CELULAR_NO_DE_CEL"]:"";
$TELEFONO_CELULAR_MODELO = isset($ROWmeasignado1["TELEFONO_CELULAR_MODELO"])?$ROWmeasignado1["TELEFONO_CELULAR_MODELO"]:"";
$TELEFONO_CELULAR_MODELO_2 = isset($ROWmeasignado1["TELEFONO_CELULAR_MODELO_2"])?$ROWmeasignado1["TELEFONO_CELULAR_MODELO_2"]:"";
$TELEFONO_CELULAR_NUMERO_DE_SERIE = isset($ROWmeasignado1["TELEFONO_CELULAR_NUMERO_DE_SERIE"])?$ROWmeasignado1["TELEFONO_CELULAR_NUMERO_DE_SERIE"]:"";
$DIADEMA_MARCA = isset($ROWmeasignado1["DIADEMA_MARCA"])?$ROWmeasignado1["DIADEMA_MARCA"]:"";
$DIADEMA_NO_DE_CEL = isset($ROWmeasignado1["DIADEMA_NO_DE_CEL"])?$ROWmeasignado1["DIADEMA_NO_DE_CEL"]:"";
$DIADEMA_MODELO = isset($ROWmeasignado1["DIADEMA_MODELO"])?$ROWmeasignado1["DIADEMA_MODELO"]:"";
$DIADEMA_MODELO_2 = isset($ROWmeasignado1["DIADEMA_MODELO_2"])?$ROWmeasignado1["DIADEMA_MODELO_2"]:"";
$DIADEMA_NUMERO_DE_SERIE = isset($ROWmeasignado1["DIADEMA_NUMERO_DE_SERIE"])?$ROWmeasignado1["DIADEMA_NUMERO_DE_SERIE"]:"";
$VRIM_MARCA = isset($ROWmeasignado1["VRIM_MARCA"])?$ROWmeasignado1["VRIM_MARCA"]:"";
$VRIM_NO_DE_CEL = isset($ROWmeasignado1["VRIM_NO_DE_CEL"])?$ROWmeasignado1["VRIM_NO_DE_CEL"]:"";
$VRIM_MODELO = isset($ROWmeasignado1["VRIM_MODELO"])?$ROWmeasignado1["VRIM_MODELO"]:"";
$VRIM_MODELO2 = isset($ROWmeasignado1["VRIM_MODELO2"])?$ROWmeasignado1["VRIM_MODELO2"]:"";
$VRIM_NUMERO_DE_SERIE = isset($ROWmeasignado1["VRIM_NUMERO_DE_SERIE"])?$ROWmeasignado1["VRIM_NUMERO_DE_SERIE"]:"";
$SEGURO_CONTRA_ACCIDENTES_MARCA = isset($ROWmeasignado1["SEGURO_CONTRA_ACCIDENTES_MARCA"])?$ROWmeasignado1["SEGURO_CONTRA_ACCIDENTES_MARCA"]:"";
$SEGURO_CONTRA_ACCIDENTES_NO_DE_CEL = isset($ROWmeasignado1["SEGURO_CONTRA_ACCIDENTES_NO_DE_CEL"])?$ROWmeasignado1["SEGURO_CONTRA_ACCIDENTES_NO_DE_CEL"]:"";
$SEGURO_CONTRA_ACCIDENTES_MODELO = isset($ROWmeasignado1["SEGURO_CONTRA_ACCIDENTES_MODELO"])?$ROWmeasignado1["SEGURO_CONTRA_ACCIDENTES_MODELO"]:"";
$SEGURO_CONTRA_ACCIDENTES_MODELO_2 = isset($ROWmeasignado1["SEGURO_CONTRA_ACCIDENTES_MODELO_2"])?$ROWmeasignado1["SEGURO_CONTRA_ACCIDENTES_MODELO_2"]:"";
$SEGURO_CONTRA_ACCIDENTES_NUMERO_DE_SERIE = isset($ROWmeasignado1["SEGURO_CONTRA_ACCIDENTES_NUMERO_DE_SERIE"])?$ROWmeasignado1["SEGURO_CONTRA_ACCIDENTES_NUMERO_DE_SERIE"]:"";
$SEGURO_DE_VIDA_MARCA = isset($ROWmeasignado1["SEGURO_DE_VIDA_MARCA"])?$ROWmeasignado1["SEGURO_DE_VIDA_MARCA"]:"";
$SEGURO_DE_VIDA_NO_DE_CEL = isset($ROWmeasignado1["SEGURO_DE_VIDA_NO_DE_CEL"])?$ROWmeasignado1["SEGURO_DE_VIDA_NO_DE_CEL"]:"";
$SEGURO_DE_VIDA_MODELO = isset($ROWmeasignado1["SEGURO_DE_VIDA_MODELO"])?$ROWmeasignado1["SEGURO_DE_VIDA_MODELO"]:"";
$SEGURO_DE_VIDA_MODELO_2 = isset($ROWmeasignado1["SEGURO_DE_VIDA_MODELO_2"])?$ROWmeasignado1["SEGURO_DE_VIDA_MODELO_2"]:"";
$SEGURO_DE_VIDA_NUMERO_DE_SERIE = isset($ROWmeasignado1["SEGURO_DE_VIDA_NUMERO_DE_SERIE"])?$ROWmeasignado1["SEGURO_DE_VIDA_NUMERO_DE_SERIE"]:"";
$SEGURO_DE_GASTOS_MEDICOS_MAYORES_MARCA = isset($ROWmeasignado1["SEGURO_DE_GASTOS_MEDICOS_MAYORES_MARCA"])?$ROWmeasignado1["SEGURO_DE_GASTOS_MEDICOS_MAYORES_MARCA"]:"";
$SEGURO_DE_GASTOS_MEDICOS_NO_DE_CEL = isset($ROWmeasignado1["SEGURO_DE_GASTOS_MEDICOS_NO_DE_CEL"])?$ROWmeasignado1["SEGURO_DE_GASTOS_MEDICOS_NO_DE_CEL"]:"";
$SEGURO_DE_GASTOS_MEDICOS_MODELO = isset($ROWmeasignado1["SEGURO_DE_GASTOS_MEDICOS_MODELO"])?$ROWmeasignado1["SEGURO_DE_GASTOS_MEDICOS_MODELO"]:"";
$SEGURO_DE_GASTOS_MEDICOS_MODELO_2 = isset($ROWmeasignado1["SEGURO_DE_GASTOS_MEDICOS_MODELO_2"])?$ROWmeasignado1["SEGURO_DE_GASTOS_MEDICOS_MODELO_2"]:"";
$SEGURO_DE_GASTOS_MEDICOS_NUMERO_DE_SERIE = isset($ROWmeasignado1["SEGURO_DE_GASTOS_MEDICOS_NUMERO_DE_SERIE"])?$ROWmeasignado1["SEGURO_DE_GASTOS_MEDICOS_NUMERO_DE_SERIE"]:"";
$TARJETA_DE_VALES_DE_DESPENSA_MARCA = isset($ROWmeasignado1["TARJETA_DE_VALES_DE_DESPENSA_MARCA"])?$ROWmeasignado1["TARJETA_DE_VALES_DE_DESPENSA_MARCA"]:"";
$TARJETA_DE_VALES_DE_DESPENSA_NO_DE_CEL = isset($ROWmeasignado1["TARJETA_DE_VALES_DE_DESPENSA_NO_DE_CEL"])?$ROWmeasignado1["TARJETA_DE_VALES_DE_DESPENSA_NO_DE_CEL"]:"";
$TARJETA_DE_VALES_DE_DESPENSA_MODELO = isset($ROWmeasignado1["TARJETA_DE_VALES_DE_DESPENSA_MODELO"])?$ROWmeasignado1["TARJETA_DE_VALES_DE_DESPENSA_MODELO"]:"";
$TARJETA_DE_VALES_DE_DESPENSA_MODELO_2 = isset($ROWmeasignado1["TARJETA_DE_VALES_DE_DESPENSA_MODELO_2"])?$ROWmeasignado1["TARJETA_DE_VALES_DE_DESPENSA_MODELO_2"]:"";
$TARJETA_DE_VALES_DE_DESPENSA_NUMERO_DE_SERIE = isset($ROWmeasignado1["TARJETA_DE_VALES_DE_DESPENSA_NUMERO_DE_SERIE"])?$ROWmeasignado1["TARJETA_DE_VALES_DE_DESPENSA_NUMERO_DE_SERIE"]:"";
$TARJETA_VALES_GASOLINA_MARCA = isset($ROWmeasignado1["TARJETA_VALES_GASOLINA_MARCA"])?$ROWmeasignado1["TARJETA_VALES_GASOLINA_MARCA"]:"";
$TARJETA_VALES_GASOLINA_NO_DE_CEL = isset($ROWmeasignado1["TARJETA_VALES_GASOLINA_NO_DE_CEL"])?$ROWmeasignado1["TARJETA_VALES_GASOLINA_NO_DE_CEL"]:"";
$TARJETA_VALES_GASOLINA_MODELO = isset($ROWmeasignado1["TARJETA_VALES_GASOLINA_MODELO"])?$ROWmeasignado1["TARJETA_VALES_GASOLINA_MODELO"]:"";
$TARJETA_VALES_GASOLINA_MODELO_2 = isset($ROWmeasignado1["TARJETA_VALES_GASOLINA_MODELO_2"])?$ROWmeasignado1["TARJETA_VALES_GASOLINA_MODELO_2"]:"";
$TARJETA_VALES_GASOLINA_NUMERO_DE_SERIE = isset($ROWmeasignado1["TARJETA_VALES_GASOLINA_NUMERO_DE_SERIE"])?$ROWmeasignado1["TARJETA_VALES_GASOLINA_NUMERO_DE_SERIE"]:"";
$COMPUTADORA_FECHA_DE_ENTREGA = isset($ROWmeasignado1["COMPUTADORA_FECHA_DE_ENTREGA"])?$ROWmeasignado1["COMPUTADORA_FECHA_DE_ENTREGA"]:"";
$COMPUTADORA_FECHA_DE_DEVOLUCION = isset($ROWmeasignado1["COMPUTADORA_FECHA_DE_DEVOLUCION"])?$ROWmeasignado1["COMPUTADORA_FECHA_DE_DEVOLUCION"]:"";
$COMPUTADORA_OBSERVACIONES = isset($ROWmeasignado1["COMPUTADORA_OBSERVACIONES"])?$ROWmeasignado1["COMPUTADORA_OBSERVACIONES"]:"";
$PANTALLA_FECHA_DE_ENTREGA = isset($ROWmeasignado1["PANTALLA_FECHA_DE_ENTREGA"])?$ROWmeasignado1["PANTALLA_FECHA_DE_ENTREGA"]:"";
$PANTALLA_FECHA_DE_DEVOLUCION = isset($ROWmeasignado1["PANTALLA_FECHA_DE_DEVOLUCION"])?$ROWmeasignado1["PANTALLA_FECHA_DE_DEVOLUCION"]:"";
$PANTALLA_OBSERVACIONES = isset($ROWmeasignado1["PANTALLA_OBSERVACIONES"])?$ROWmeasignado1["PANTALLA_OBSERVACIONES"]:"";
$MOUSE_FECHA_DE_ENTREGA = isset($ROWmeasignado1["MOUSE_FECHA_DE_ENTREGA"])?$ROWmeasignado1["MOUSE_FECHA_DE_ENTREGA"]:"";
$MOUSE_FECHA_DE_DEVOLUCION = isset($ROWmeasignado1["MOUSE_FECHA_DE_DEVOLUCION"])?$ROWmeasignado1["MOUSE_FECHA_DE_DEVOLUCION"]:"";
$MOUSE_OBSERVACIONES = isset($ROWmeasignado1["MOUSE_OBSERVACIONES"])?$ROWmeasignado1["MOUSE_OBSERVACIONES"]:"";
$DISCO_EXTERNO_FECHA_DE_ENTREGA = isset($ROWmeasignado1["DISCO_EXTERNO_FECHA_DE_ENTREGA"])?$ROWmeasignado1["DISCO_EXTERNO_FECHA_DE_ENTREGA"]:"";
$DISCO_EXTERNO_FECHA_DE_DEVOLUCION = isset($ROWmeasignado1["DISCO_EXTERNO_FECHA_DE_DEVOLUCION"])?$ROWmeasignado1["DISCO_EXTERNO_FECHA_DE_DEVOLUCION"]:"";
$DISCO_EXTERNO_OBSERVACIONES = isset($ROWmeasignado1["DISCO_EXTERNO_OBSERVACIONES"])?$ROWmeasignado1["DISCO_EXTERNO_OBSERVACIONES"]:"";
$MATERIAL_EQUIPO_ASIGNADO_OTRO_FECHA_DE_ENTREGA = isset($ROWmeasignado1["MATERIAL_EQUIPO_ASIGNADO_OTRO_FECHA_DE_ENTREGA"])?$ROWmeasignado1["MATERIAL_EQUIPO_ASIGNADO_OTRO_FECHA_DE_ENTREGA"]:"";
$MATERIAL_EQUIPO_ASIGNADO_OTRO_FECHA_DE_DEVOLUCION = isset($ROWmeasignado1["MATERIAL_EQUIPO_ASIGNADO_OTRO_FECHA_DE_DEVOLUCION"])?$ROWmeasignado1["MATERIAL_EQUIPO_ASIGNADO_OTRO_FECHA_DE_DEVOLUCION"]:"";
$MATERIAL_EQUIPO_ASIGNADO_OTRO_OBSERVACIONES = isset($ROWmeasignado1["MATERIAL_EQUIPO_ASIGNADO_OTRO_OBSERVACIONES"])?$ROWmeasignado1["MATERIAL_EQUIPO_ASIGNADO_OTRO_OBSERVACIONES"]:"";
$MATERIAL_EQUIPO_ASIGNADO_OTRO_FECHA_DE_ENTREGA_2 = isset($ROWmeasignado1["MATERIAL_EQUIPO_ASIGNADO_OTRO_FECHA_DE_ENTREGA_2"])?$ROWmeasignado1["MATERIAL_EQUIPO_ASIGNADO_OTRO_FECHA_DE_ENTREGA_2"]:"";
$MATERIAL_EQUIPO_ASIGNADO_OTRO_FECHA_DE_DEVOLUCION_2 = isset($ROWmeasignado1["MATERIAL_EQUIPO_ASIGNADO_OTRO_FECHA_DE_DEVOLUCION_2"])?$ROWmeasignado1["MATERIAL_EQUIPO_ASIGNADO_OTRO_FECHA_DE_DEVOLUCION_2"]:"";
$MATERIAL_EQUIPO_ASIGNADO_OTRO_OBSERVACIONES_2 = isset($ROWmeasignado1["MATERIAL_EQUIPO_ASIGNADO_OTRO_OBSERVACIONES_2"])?$ROWmeasignado1["MATERIAL_EQUIPO_ASIGNADO_OTRO_OBSERVACIONES_2"]:"";
$TELEFONO_CELULAR_FECHA_DE_ENTREGA = isset($ROWmeasignado1["TELEFONO_CELULAR_FECHA_DE_ENTREGA"])?$ROWmeasignado1["TELEFONO_CELULAR_FECHA_DE_ENTREGA"]:"";
$TELEFONO_CELULAR_FECHA_DE_DEVOLUCION = isset($ROWmeasignado1["TELEFONO_CELULAR_FECHA_DE_DEVOLUCION"])?$ROWmeasignado1["TELEFONO_CELULAR_FECHA_DE_DEVOLUCION"]:"";
$TELEFONO_CELULAR_OBSERVACIONES = isset($ROWmeasignado1["TELEFONO_CELULAR_OBSERVACIONES"])?$ROWmeasignado1["TELEFONO_CELULAR_OBSERVACIONES"]:"";
$DIADEMA_FECHA_DE_ENTREGA = isset($ROWmeasignado1["DIADEMA_FECHA_DE_ENTREGA"])?$ROWmeasignado1["DIADEMA_FECHA_DE_ENTREGA"]:"";
$DIADEMA_FECHA_DE_DEVOLUCION = isset($ROWmeasignado1["DIADEMA_FECHA_DE_DEVOLUCION"])?$ROWmeasignado1["DIADEMA_FECHA_DE_DEVOLUCION"]:"";
$DIADEMA_OBSERVACIONES = isset($ROWmeasignado1["DIADEMA_OBSERVACIONES"])?$ROWmeasignado1["DIADEMA_OBSERVACIONES"]:"";
$VRIM_FECHA_DE_ENTREGA = isset($ROWmeasignado1["VRIM_FECHA_DE_ENTREGA"])?$ROWmeasignado1["VRIM_FECHA_DE_ENTREGA"]:"";
$VRIM_FECHA_DE_DEVOLUCION = isset($ROWmeasignado1["VRIM_FECHA_DE_DEVOLUCION"])?$ROWmeasignado1["VRIM_FECHA_DE_DEVOLUCION"]:"";
$VRIM_OBSERVACIONES = isset($ROWmeasignado1["VRIM_OBSERVACIONES"])?$ROWmeasignado1["VRIM_OBSERVACIONES"]:"";
$SEGURO_CONTRA_ACCIDENTES_FECHA_DE_ENTREGA = isset($ROWmeasignado1["SEGURO_CONTRA_ACCIDENTES_FECHA_DE_ENTREGA"])?$ROWmeasignado1["SEGURO_CONTRA_ACCIDENTES_FECHA_DE_ENTREGA"]:"";
$SEGURO_CONTRA_ACCIDENTES_FECHA_DE_DEVOLUCION = isset($ROWmeasignado1["SEGURO_CONTRA_ACCIDENTES_FECHA_DE_DEVOLUCION"])?$ROWmeasignado1["SEGURO_CONTRA_ACCIDENTES_FECHA_DE_DEVOLUCION"]:"";
$SEGURO_CONTRA_ACCIDENTES_OBSERVACIONES = isset($ROWmeasignado1["SEGURO_CONTRA_ACCIDENTES_OBSERVACIONES"])?$ROWmeasignado1["SEGURO_CONTRA_ACCIDENTES_OBSERVACIONES"]:"";
$SEGURO_DE_VIDA_FECHA_DE_ENTREGA = isset($ROWmeasignado1["SEGURO_DE_VIDA_FECHA_DE_ENTREGA"])?$ROWmeasignado1["SEGURO_DE_VIDA_FECHA_DE_ENTREGA"]:"";
$SEGURO_DE_VIDA_FECHA_DE_DEVOLUCION = isset($ROWmeasignado1["SEGURO_DE_VIDA_FECHA_DE_DEVOLUCION"])?$ROWmeasignado1["SEGURO_DE_VIDA_FECHA_DE_DEVOLUCION"]:"";
$SEGURO_DE_VIDA_OBSERVACIONES = isset($ROWmeasignado1["SEGURO_DE_VIDA_OBSERVACIONES"])?$ROWmeasignado1["SEGURO_DE_VIDA_OBSERVACIONES"]:"";
$SEGURO_DE_GASTOS_MEDICOS_FECHA_DE_ENTREGA = isset($ROWmeasignado1["SEGURO_DE_GASTOS_MEDICOS_FECHA_DE_ENTREGA"])?$ROWmeasignado1["SEGURO_DE_GASTOS_MEDICOS_FECHA_DE_ENTREGA"]:"";
$SEGURO_DE_GASTOS_MEDICOS_FECHA_DE_DEVOLUCION = isset($ROWmeasignado1["SEGURO_DE_GASTOS_MEDICOS_FECHA_DE_DEVOLUCION"])?$ROWmeasignado1["SEGURO_DE_GASTOS_MEDICOS_FECHA_DE_DEVOLUCION"]:"";
$SEGURO_DE_GASTOS_MEDICOS_OBSERVACIONES = isset($ROWmeasignado1["SEGURO_DE_GASTOS_MEDICOS_OBSERVACIONES"])?$ROWmeasignado1["SEGURO_DE_GASTOS_MEDICOS_OBSERVACIONES"]:"";
$TARJETA_DE_VALES_DE_DESPENSA_FECHA_DE_ENTREGA = isset($ROWmeasignado1["TARJETA_DE_VALES_DE_DESPENSA_FECHA_DE_ENTREGA"])?$ROWmeasignado1["TARJETA_DE_VALES_DE_DESPENSA_FECHA_DE_ENTREGA"]:"";
$TARJETA_DE_VALES_DE_DESPENSA_FECHA_DE_DEVOLUCION = isset($ROWmeasignado1["TARJETA_DE_VALES_DE_DESPENSA_FECHA_DE_DEVOLUCION"])?$ROWmeasignado1["TARJETA_DE_VALES_DE_DESPENSA_FECHA_DE_DEVOLUCION"]:"";
$TARJETA_DE_VALES_DE_DESPENSA_OBSERVACIONES = isset($ROWmeasignado1["TARJETA_DE_VALES_DE_DESPENSA_OBSERVACIONES"])?$ROWmeasignado1["TARJETA_DE_VALES_DE_DESPENSA_OBSERVACIONES"]:"";
$TARJETA_DE_VALES_GASOLINA_FECHA_DE_ENTREGA = isset($ROWmeasignado1["TARJETA_DE_VALES_GASOLINA_FECHA_DE_ENTREGA"])?$ROWmeasignado1["TARJETA_DE_VALES_GASOLINA_FECHA_DE_ENTREGA"]:"";
$TARJETA_DE_VALES_GASOLINA_FECHA_DE_DEVOLUCION = isset($ROWmeasignado1["TARJETA_DE_VALES_GASOLINA_FECHA_DE_DEVOLUCION"])?$ROWmeasignado1["TARJETA_DE_VALES_GASOLINA_FECHA_DE_DEVOLUCION"]:"";
$TARJETA_DE_VALES_GASOLINA_OBSERVACIONES = isset($ROWmeasignado1["TARJETA_DE_VALES_GASOLINA_OBSERVACIONES"])?$ROWmeasignado1["TARJETA_DE_VALES_GASOLINA_OBSERVACIONES"]:"";
$CMEASIGNADO1 = isset($ROWmeasignado1["CMEASIGNADO1"])?$ROWmeasignado1["CMEASIGNADO1"]:"";


$ROWmeasignado2 = $conexion->variablesMEASIGNADO2();
$ROW2= array( );
//print_r($ROW);
$ROWfmeasignado2a1 = $conexion->contadorporcentaje($ROWmeasignado2,$ROW2);
$TALLA_CAMISA_MARCA = isset($ROWmeasignado2["TALLA_CAMISA_MARCA"])?$ROWmeasignado2["TALLA_CAMISA_MARCA"]:"";
$TALLA_CAMISA_NO_DE_CEL = isset($ROWmeasignado2["TALLA_CAMISA_NO_DE_CEL"])?$ROWmeasignado2["TALLA_CAMISA_NO_DE_CEL"]:"";
$TALLA_CAMISA_MODELO = isset($ROWmeasignado2["TALLA_CAMISA_MODELO"])?$ROWmeasignado2["TALLA_CAMISA_MODELO"]:"";
$TALLA_CAMISA_MODELO_2 = isset($ROWmeasignado2["TALLA_CAMISA_MODELO_2"])?$ROWmeasignado2["TALLA_CAMISA_MODELO_2"]:"";
$TALLA_CAMISA_NUMERO_DE_SERIE = isset($ROWmeasignado2["TALLA_CAMISA_NUMERO_DE_SERIE"])?$ROWmeasignado2["TALLA_CAMISA_NUMERO_DE_SERIE"]:"";
$TALLA_PLAYERA_POLO_MARCA = isset($ROWmeasignado2["TALLA_PLAYERA_POLO_MARCA"])?$ROWmeasignado2["TALLA_PLAYERA_POLO_MARCA"]:"";
$TALLA_PLAYERA_NO_DE_CEL = isset($ROWmeasignado2["TALLA_PLAYERA_NO_DE_CEL"])?$ROWmeasignado2["TALLA_PLAYERA_NO_DE_CEL"]:"";
$TALLA_PLAYERA_MODELO = isset($ROWmeasignado2["TALLA_PLAYERA_MODELO"])?$ROWmeasignado2["TALLA_PLAYERA_MODELO"]:"";
$TALLA_PLAYERA_MODELO_2 = isset($ROWmeasignado2["TALLA_PLAYERA_MODELO_2"])?$ROWmeasignado2["TALLA_PLAYERA_MODELO_2"]:"";
$TALLA_PLAYERA_NUMERO_DE_SERIE = isset($ROWmeasignado2["TALLA_PLAYERA_NUMERO_DE_SERIE"])?$ROWmeasignado2["TALLA_PLAYERA_NUMERO_DE_SERIE"]:"";
$TALLA_PLAYERA_MARCA = isset($ROWmeasignado2["TALLA_PLAYERA_MARCA"])?$ROWmeasignado2["TALLA_PLAYERA_MARCA"]:"";
$TALLA_PANTALON_MARCA = isset($ROWmeasignado2["TALLA_PANTALON_MARCA"])?$ROWmeasignado2["TALLA_PANTALON_MARCA"]:"";
$TALLA_PANTALON_NO_DE_CEL = isset($ROWmeasignado2["TALLA_PANTALON_NO_DE_CEL"])?$ROWmeasignado2["TALLA_PANTALON_NO_DE_CEL"]:"";
$TALLA_PANTALON_MODELO = isset($ROWmeasignado2["TALLA_PANTALON_MODELO"])?$ROWmeasignado2["TALLA_PANTALON_MODELO"]:"";
$TALLA_PANTALON_MODELO_2 = isset($ROWmeasignado2["TALLA_PANTALON_MODELO_2"])?$ROWmeasignado2["TALLA_PANTALON_MODELO_2"]:"";
$TALLA_PANTALON_NUMERO_DE_SERIE = isset($ROWmeasignado2["TALLA_PANTALON_NUMERO_DE_SERIE"])?$ROWmeasignado2["TALLA_PANTALON_NUMERO_DE_SERIE"]:"";
$TALLA_CHAMARRA_MARCA = isset($ROWmeasignado2["TALLA_CHAMARRA_MARCA"])?$ROWmeasignado2["TALLA_CHAMARRA_MARCA"]:"";
$TALLA_CHAMARRA_NO_DE_CEL = isset($ROWmeasignado2["TALLA_CHAMARRA_NO_DE_CEL"])?$ROWmeasignado2["TALLA_CHAMARRA_NO_DE_CEL"]:"";
$TALLA_CHAMARRA_MODELO = isset($ROWmeasignado2["TALLA_CHAMARRA_MODELO"])?$ROWmeasignado2["TALLA_CHAMARRA_MODELO"]:"";
$TALLA_CHAMARRA_MODELO_2 = isset($ROWmeasignado2["TALLA_CHAMARRA_MODELO_2"])?$ROWmeasignado2["TALLA_CHAMARRA_MODELO_2"]:"";
$TALLA_CHAMARRA_NUMERO_DE_SERIE = isset($ROWmeasignado2["TALLA_CHAMARRA_NUMERO_DE_SERIE"])?$ROWmeasignado2["TALLA_CHAMARRA_NUMERO_DE_SERIE"]:"";
$TALLA_CHALECO_MARCA = isset($ROWmeasignado2["TALLA_CHALECO_MARCA"])?$ROWmeasignado2["TALLA_CHALECO_MARCA"]:"";
$TALLA_CHALECO_NO_DE_CEL = isset($ROWmeasignado2["TALLA_CHALECO_NO_DE_CEL"])?$ROWmeasignado2["TALLA_CHALECO_NO_DE_CEL"]:"";
$TALLA_CHALECO_MODELO = isset($ROWmeasignado2["TALLA_CHALECO_MODELO"])?$ROWmeasignado2["TALLA_CHALECO_MODELO"]:"";
$TALLA_CHALECO_MODELO_2 = isset($ROWmeasignado2["TALLA_CHALECO_MODELO_2"])?$ROWmeasignado2["TALLA_CHALECO_MODELO_2"]:"";
$TALLA_CHALECO_NUMERO_DE_SERIE = isset($ROWmeasignado2["TALLA_CHALECO_NUMERO_DE_SERIE"])?$ROWmeasignado2["TALLA_CHALECO_NUMERO_DE_SERIE"]:"";
$TALLA_TENIS_MARCA = isset($ROWmeasignado2["TALLA_TENIS_MARCA"])?$ROWmeasignado2["TALLA_TENIS_MARCA"]:"";
$TALLA_TENIS_NO_DE_CEL = isset($ROWmeasignado2["TALLA_TENIS_NO_DE_CEL"])?$ROWmeasignado2["TALLA_TENIS_NO_DE_CEL"]:"";
$TALLA_TENIS_MODELO = isset($ROWmeasignado2["TALLA_TENIS_MODELO"])?$ROWmeasignado2["TALLA_TENIS_MODELO"]:"";
$TALLA_TENIS_MODELO_2 = isset($ROWmeasignado2["TALLA_TENIS_MODELO_2"])?$ROWmeasignado2["TALLA_TENIS_MODELO_2"]:"";
$TALLA_TENIS_NUMERO_DE_SERIE = isset($ROWmeasignado2["TALLA_TENIS_NUMERO_DE_SERIE"])?$ROWmeasignado2["TALLA_TENIS_NUMERO_DE_SERIE"]:"";
$GORRA_MARCA = isset($ROWmeasignado2["GORRA_MARCA"])?$ROWmeasignado2["GORRA_MARCA"]:"";
$GORRA_NO_DE_CEL = isset($ROWmeasignado2["GORRA_NO_DE_CEL"])?$ROWmeasignado2["GORRA_NO_DE_CEL"]:"";
$GORRA_MODELO = isset($ROWmeasignado2["GORRA_MODELO"])?$ROWmeasignado2["GORRA_MODELO"]:"";
$GORRA_MODELO_2 = isset($ROWmeasignado2["GORRA_MODELO_2"])?$ROWmeasignado2["GORRA_MODELO_2"]:"";
$GORRA_NUMERO_DE_SERIE = isset($ROWmeasignado2["GORRA_NUMERO_DE_SERIE"])?$ROWmeasignado2["GORRA_NUMERO_DE_SERIE"]:"";
$MALETA_GRANDE_MARCA = isset($ROWmeasignado2["MALETA_GRANDE_MARCA"])?$ROWmeasignado2["MALETA_GRANDE_MARCA"]:"";
$MALETA_GRANDE_NO_DE_CEL = isset($ROWmeasignado2["MALETA_GRANDE_NO_DE_CEL"])?$ROWmeasignado2["MALETA_GRANDE_NO_DE_CEL"]:"";
$MALETA_GRANDE_MODELO = isset($ROWmeasignado2["MALETA_GRANDE_MODELO"])?$ROWmeasignado2["MALETA_GRANDE_MODELO"]:"";
$MALETA_GRANDE_MODELO_2 = isset($ROWmeasignado2["MALETA_GRANDE_MODELO_2"])?$ROWmeasignado2["MALETA_GRANDE_MODELO_2"]:"";
$MALETA_GRANDE_NUMERO_DE_SERIE = isset($ROWmeasignado2["MALETA_GRANDE_NUMERO_DE_SERIE"])?$ROWmeasignado2["MALETA_GRANDE_NUMERO_DE_SERIE"]:"";
$MALETA_MEDIANA_MARCA = isset($ROWmeasignado2["MALETA_MEDIANA_MARCA"])?$ROWmeasignado2["MALETA_MEDIANA_MARCA"]:"";
$MALETA_MEDIANA_NO_DE_CEL = isset($ROWmeasignado2["MALETA_MEDIANA_NO_DE_CEL"])?$ROWmeasignado2["MALETA_MEDIANA_NO_DE_CEL"]:"";
$MALETA_MEDIANA_MODELO = isset($ROWmeasignado2["MALETA_MEDIANA_MODELO"])?$ROWmeasignado2["MALETA_MEDIANA_MODELO"]:"";
$MALETA_MEDIANA_MODELO_2 = isset($ROWmeasignado2["MALETA_MEDIANA_MODELO_2"])?$ROWmeasignado2["MALETA_MEDIANA_MODELO_2"]:"";
$MALETA_MEDIANA_NUMERO_DE_SERIE = isset($ROWmeasignado2["MALETA_MEDIANA_NUMERO_DE_SERIE"])?$ROWmeasignado2["MALETA_MEDIANA_NUMERO_DE_SERIE"]:"";
$MALETA_CHICA_MARCA = isset($ROWmeasignado2["MALETA_CHICA_MARCA"])?$ROWmeasignado2["MALETA_CHICA_MARCA"]:"";
$MALETA_CHICA_NO_DE_CEL = isset($ROWmeasignado2["MALETA_CHICA_NO_DE_CEL"])?$ROWmeasignado2["MALETA_CHICA_NO_DE_CEL"]:"";
$MALETA_CHICA_MODELO = isset($ROWmeasignado2["MALETA_CHICA_MODELO"])?$ROWmeasignado2["MALETA_CHICA_MODELO"]:"";
$MALETA_CHICA_MODELO_2 = isset($ROWmeasignado2["MALETA_CHICA_MODELO_2"])?$ROWmeasignado2["MALETA_CHICA_MODELO_2"]:"";
$MALETA_CHICA_NUMERO_DE_SERIE = isset($ROWmeasignado2["MALETA_CHICA_NUMERO_DE_SERIE"])?$ROWmeasignado2["MALETA_CHICA_NUMERO_DE_SERIE"]:"";
$BACK_PACK_MARCA = isset($ROWmeasignado2["BACK_PACK_MARCA"])?$ROWmeasignado2["BACK_PACK_MARCA"]:"";
$BACK_PACK_NO_DE_CEL = isset($ROWmeasignado2["BACK_PACK_NO_DE_CEL"])?$ROWmeasignado2["BACK_PACK_NO_DE_CEL"]:"";
$BACK_PACK_MODELO = isset($ROWmeasignado2["BACK_PACK_MODELO"])?$ROWmeasignado2["BACK_PACK_MODELO"]:"";
$BACK_PACK_MODELO_2 = isset($ROWmeasignado2["BACK_PACK_MODELO_2"])?$ROWmeasignado2["BACK_PACK_MODELO_2"]:"";
$BACK_PACK_NUMERO_DE_SERIE = isset($ROWmeasignado2["BACK_PACK_NUMERO_DE_SERIE"])?$ROWmeasignado2["BACK_PACK_NUMERO_DE_SERIE"]:"";
$OTROS_MARCA = isset($ROWmeasignado2["OTROS_MARCA"])?$ROWmeasignado2["OTROS_MARCA"]:"";
$OTROS_NO_DE_CEL = isset($ROWmeasignado2["OTROS_NO_DE_CEL"])?$ROWmeasignado2["OTROS_NO_DE_CEL"]:"";
$OTROS_MODELO = isset($ROWmeasignado2["OTROS_MODELO"])?$ROWmeasignado2["OTROS_MODELO"]:"";
$OTROS_MODELO_2 = isset($ROWmeasignado2["OTROS_MODELO_2"])?$ROWmeasignado2["OTROS_MODELO_2"]:"";
$OTROS_NUMERO_DE_SERIE = isset($ROWmeasignado2["OTROS_NUMERO_DE_SERIE"])?$ROWmeasignado2["OTROS_NUMERO_DE_SERIE"]:"";
$OTROS_2_MARCA = isset($ROWmeasignado2["OTROS_2_MARCA"])?$ROWmeasignado2["OTROS_2_MARCA"]:"";
$OTROS_2_NO_DE_CEL = isset($ROWmeasignado2["OTROS_2_NO_DE_CEL"])?$ROWmeasignado2["OTROS_2_NO_DE_CEL"]:"";
$OTROS_2_MODELO = isset($ROWmeasignado2["OTROS_2_MODELO"])?$ROWmeasignado2["OTROS_2_MODELO"]:"";
$OTROS_2_MODELO_2 = isset($ROWmeasignado2["OTROS_2_MODELO_2"])?$ROWmeasignado2["OTROS_2_MODELO_2"]:"";
$OTROS_2_NUMERO_DE_SERIE = isset($ROWmeasignado2["OTROS_2_NUMERO_DE_SERIE"])?$ROWmeasignado2["OTROS_2_NUMERO_DE_SERIE"]:"";
$OTROS_3_MARCA = isset($ROWmeasignado2["OTROS_3_MARCA"])?$ROWmeasignado2["OTROS_3_MARCA"]:"";
$OTROS_3_NO_DE_CEL = isset($ROWmeasignado2["OTROS_3_NO_DE_CEL"])?$ROWmeasignado2["OTROS_3_NO_DE_CEL"]:"";
$OTROS_3_MODELO = isset($ROWmeasignado2["OTROS_3_MODELO"])?$ROWmeasignado2["OTROS_3_MODELO"]:"";
$OTROS_3_MODELO_2 = isset($ROWmeasignado2["OTROS_3_MODELO_2"])?$ROWmeasignado2["OTROS_3_MODELO_2"]:"";
$OTROS_3_NUMERO_DE_SERIE = isset($ROWmeasignado2["OTROS_3_NUMERO_DE_SERIE"])?$ROWmeasignado2["OTROS_3_NUMERO_DE_SERIE"]:"";
$OTROS_4_MARCA = isset($ROWmeasignado2["OTROS_4_MARCA"])?$ROWmeasignado2["OTROS_4_MARCA"]:"";
$OTROS_4_NO_DE_CEL = isset($ROWmeasignado2["OTROS_4_NO_DE_CEL"])?$ROWmeasignado2["OTROS_4_NO_DE_CEL"]:"";
$OTROS_4_MODELO = isset($ROWmeasignado2["OTROS_4_MODELO"])?$ROWmeasignado2["OTROS_4_MODELO"]:"";
$OTROS_4_MODELO_2 = isset($ROWmeasignado2["OTROS_4_MODELO_2"])?$ROWmeasignado2["OTROS_4_MODELO_2"]:"";
$OTROS_4_NUMERO_DE_SERIE = isset($ROWmeasignado2["OTROS_4_NUMERO_DE_SERIE"])?$ROWmeasignado2["OTROS_4_NUMERO_DE_SERIE"]:"";
$TALLA_CAMISA_FECHA_DE_ENTREGA = isset($ROWmeasignado2["TALLA_CAMISA_FECHA_DE_ENTREGA"])?$ROWmeasignado2["TALLA_CAMISA_FECHA_DE_ENTREGA"]:"";
$TALLA_CAMISA_FECHA_DE_DEVOLUCION = isset($ROWmeasignado2["TALLA_CAMISA_FECHA_DE_DEVOLUCION"])?$ROWmeasignado2["TALLA_CAMISA_FECHA_DE_DEVOLUCION"]:"";
$TALLA_CAMISA_OBSERVACIONES = isset($ROWmeasignado2["TALLA_CAMISA_OBSERVACIONES"])?$ROWmeasignado2["TALLA_CAMISA_OBSERVACIONES"]:"";
$TALLA_PLAYERA_FECHA_DE_ENTREGA = isset($ROWmeasignado2["TALLA_PLAYERA_FECHA_DE_ENTREGA"])?$ROWmeasignado2["TALLA_PLAYERA_FECHA_DE_ENTREGA"]:"";
$TALLA_PLAYERA_FECHA_DE_DEVOLUCION = isset($ROWmeasignado2["TALLA_PLAYERA_FECHA_DE_DEVOLUCION"])?$ROWmeasignado2["TALLA_PLAYERA_FECHA_DE_DEVOLUCION"]:"";
$TALLA_PLAYERA_OBSERVACIONES = isset($ROWmeasignado2["TALLA_PLAYERA_OBSERVACIONES"])?$ROWmeasignado2["TALLA_PLAYERA_OBSERVACIONES"]:"";

$PLAYERA_FECHA_polo_ENTREGA = isset($ROWmeasignado2["PLAYERA_FECHA_polo_ENTREGA"])?$ROWmeasignado2["PLAYERA_FECHA_polo_ENTREGA"]:"";
$PLAYERA_FECHA_polo_DEVOLUCION = isset($ROWmeasignado2["PLAYERA_FECHA_polo_DEVOLUCION"])?$ROWmeasignado2["PLAYERA_FECHA_polo_DEVOLUCION"]:"";
$PLAYERA_polo_OBSERVACIONES = isset($ROWmeasignado2["PLAYERA_polo_OBSERVACIONES"])?$ROWmeasignado2["PLAYERA_polo_OBSERVACIONES"]:"";


$TALLA_PANTALON_FECHA_DE_ENTREGA = isset($ROWmeasignado2["TALLA_PANTALON_FECHA_DE_ENTREGA"])?$ROWmeasignado2["TALLA_PANTALON_FECHA_DE_ENTREGA"]:"";
$TALLA_PANTALON_FECHA_DE_DEVOLUCION = isset($ROWmeasignado2["TALLA_PANTALON_FECHA_DE_DEVOLUCION"])?$ROWmeasignado2["TALLA_PANTALON_FECHA_DE_DEVOLUCION"]:"";
$TALLA_PANTALON_OBSERVACIONES = isset($ROWmeasignado2["TALLA_PANTALON_OBSERVACIONES"])?$ROWmeasignado2["TALLA_PANTALON_OBSERVACIONES"]:"";
$TALLA_CHAMARRA_FECHA_DE_ENTREGA = isset($ROWmeasignado2["TALLA_CHAMARRA_FECHA_DE_ENTREGA"])?$ROWmeasignado2["TALLA_CHAMARRA_FECHA_DE_ENTREGA"]:"";
$TALLA_CHAMARRA_FECHA_DE_DEVOLUCION = isset($ROWmeasignado2["TALLA_CHAMARRA_FECHA_DE_DEVOLUCION"])?$ROWmeasignado2["TALLA_CHAMARRA_FECHA_DE_DEVOLUCION"]:"";
$TALLA_CHAMARRA_OBSERVACIONES = isset($ROWmeasignado2["TALLA_CHAMARRA_OBSERVACIONES"])?$ROWmeasignado2["TALLA_CHAMARRA_OBSERVACIONES"]:"";
$TALLA_CHALECO_FECHA_DE_ENTREGA = isset($ROWmeasignado2["TALLA_CHALECO_FECHA_DE_ENTREGA"])?$ROWmeasignado2["TALLA_CHALECO_FECHA_DE_ENTREGA"]:"";
$TALLA_CHALECO_FECHA_DE_DEVOLUCION = isset($ROWmeasignado2["TALLA_CHALECO_FECHA_DE_DEVOLUCION"])?$ROWmeasignado2["TALLA_CHALECO_FECHA_DE_DEVOLUCION"]:"";
$TALLA_CHALECO_OBSERVACIONES = isset($ROWmeasignado2["TALLA_CHALECO_OBSERVACIONES"])?$ROWmeasignado2["TALLA_CHALECO_OBSERVACIONES"]:"";
$TALLA_TENIS_FECHA_DE_ENTREGA = isset($ROWmeasignado2["TALLA_TENIS_FECHA_DE_ENTREGA"])?$ROWmeasignado2["TALLA_TENIS_FECHA_DE_ENTREGA"]:"";
$TALLA_TENIS_FECHA_DE_DEVOLUCION = isset($ROWmeasignado2["TALLA_TENIS_FECHA_DE_DEVOLUCION"])?$ROWmeasignado2["TALLA_TENIS_FECHA_DE_DEVOLUCION"]:"";
$TALLA_TENIS_OBSERVACIONES = isset($ROWmeasignado2["TALLA_TENIS_OBSERVACIONES"])?$ROWmeasignado2["TALLA_TENIS_OBSERVACIONES"]:"";
$GORRA_FECHA_DE_ENTREGA = isset($ROWmeasignado2["GORRA_FECHA_DE_ENTREGA"])?$ROWmeasignado2["GORRA_FECHA_DE_ENTREGA"]:"";
$GORRA_FECHA_DE_DEVOLUCION = isset($ROWmeasignado2["GORRA_FECHA_DE_DEVOLUCION"])?$ROWmeasignado2["GORRA_FECHA_DE_DEVOLUCION"]:"";
$GORRA_OBSERVACIONES = isset($ROWmeasignado2["GORRA_OBSERVACIONES"])?$ROWmeasignado2["GORRA_OBSERVACIONES"]:"";
$MALETA_GRANDE_FECHA_DE_ENTREGA = isset($ROWmeasignado2["MALETA_GRANDE_FECHA_DE_ENTREGA"])?$ROWmeasignado2["MALETA_GRANDE_FECHA_DE_ENTREGA"]:"";
$MALETA_GRANDE_FECHA_DE_DEVOLUCION = isset($ROWmeasignado2["MALETA_GRANDE_FECHA_DE_DEVOLUCION"])?$ROWmeasignado2["MALETA_GRANDE_FECHA_DE_DEVOLUCION"]:"";
$MALETA_GRANDE_OBSERVACIONES = isset($ROWmeasignado2["MALETA_GRANDE_OBSERVACIONES"])?$ROWmeasignado2["MALETA_GRANDE_OBSERVACIONES"]:"";
$MALETA_MEDIANA_FECHA_DE_ENTREGA = isset($ROWmeasignado2["MALETA_MEDIANA_FECHA_DE_ENTREGA"])?$ROWmeasignado2["MALETA_MEDIANA_FECHA_DE_ENTREGA"]:"";
$MALETA_MEDIANA_FECHA_DE_DEVOLUCION = isset($ROWmeasignado2["MALETA_MEDIANA_FECHA_DE_DEVOLUCION"])?$ROWmeasignado2["MALETA_MEDIANA_FECHA_DE_DEVOLUCION"]:"";
$MALETA_MEDIANA_OBSERVACIONES = isset($ROWmeasignado2["MALETA_MEDIANA_OBSERVACIONES"])?$ROWmeasignado2["MALETA_MEDIANA_OBSERVACIONES"]:"";
$MALETA_CHICA_FECHA_DE_ENTREGA = isset($ROWmeasignado2["MALETA_CHICA_FECHA_DE_ENTREGA"])?$ROWmeasignado2["MALETA_CHICA_FECHA_DE_ENTREGA"]:"";
$MALETA_CHICA_FECHA_DE_DEVOLUCION = isset($ROWmeasignado2["MALETA_CHICA_FECHA_DE_DEVOLUCION"])?$ROWmeasignado2["MALETA_CHICA_FECHA_DE_DEVOLUCION"]:"";
$MALETA_CHICA_OBSERVACIONES = isset($ROWmeasignado2["MALETA_CHICA_OBSERVACIONES"])?$ROWmeasignado2["MALETA_CHICA_OBSERVACIONES"]:"";
$BACK_PACK_FECHA_DE_ENTREGA = isset($ROWmeasignado2["BACK_PACK_FECHA_DE_ENTREGA"])?$ROWmeasignado2["BACK_PACK_FECHA_DE_ENTREGA"]:"";
$BACK_PACK_FECHA_DE_DEVOLUCION = isset($ROWmeasignado2["BACK_PACK_FECHA_DE_DEVOLUCION"])?$ROWmeasignado2["BACK_PACK_FECHA_DE_DEVOLUCION"]:"";
$BACK_PACK_OBSERVACIONES = isset($ROWmeasignado2["BACK_PACK_OBSERVACIONES"])?$ROWmeasignado2["BACK_PACK_OBSERVACIONES"]:"";
$OTROS_FECHA_DE_ENTREGA = isset($ROWmeasignado2["OTROS_FECHA_DE_ENTREGA"])?$ROWmeasignado2["OTROS_FECHA_DE_ENTREGA"]:"";
$OTROS_FECHA_DE_DEVOLUCION = isset($ROWmeasignado2["OTROS_FECHA_DE_DEVOLUCION"])?$ROWmeasignado2["OTROS_FECHA_DE_DEVOLUCION"]:"";
$OTROS_OBSERVACIONES = isset($ROWmeasignado2["OTROS_OBSERVACIONES"])?$ROWmeasignado2["OTROS_OBSERVACIONES"]:"";
$OTROS_2_FECHA_DE_ENTREGA = isset($ROWmeasignado2["OTROS_2_FECHA_DE_ENTREGA"])?$ROWmeasignado2["OTROS_2_FECHA_DE_ENTREGA"]:"";
$OTROS_2_FECHA_DE_DEVOLUCION = isset($ROWmeasignado2["OTROS_2_FECHA_DE_DEVOLUCION"])?$ROWmeasignado2["OTROS_2_FECHA_DE_DEVOLUCION"]:"";
$OTROS_2_OBSERVACIONES = isset($ROWmeasignado2["OTROS_2_OBSERVACIONES"])?$ROWmeasignado2["OTROS_2_OBSERVACIONES"]:"";
$OTROS_3_FECHA_DE_ENTREGA = isset($ROWmeasignado2["OTROS_3_FECHA_DE_ENTREGA"])?$ROWmeasignado2["OTROS_3_FECHA_DE_ENTREGA"]:"";
$OTROS_3_FECHA_DE_DEVOLUCION = isset($ROWmeasignado2["OTROS_3_FECHA_DE_DEVOLUCION"])?$ROWmeasignado2["OTROS_3_FECHA_DE_DEVOLUCION"]:"";
$OTROS_3_OBSERVACIONES = isset($ROWmeasignado2["OTROS_3_OBSERVACIONES"])?$ROWmeasignado2["OTROS_3_OBSERVACIONES"]:"";
$OTROS_4_FECHA_DE_ENTREGA = isset($ROWmeasignado2["OTROS_4_FECHA_DE_ENTREGA"])?$ROWmeasignado2["OTROS_4_FECHA_DE_ENTREGA"]:"";
$OTROS_4_FECHA_DE_DEVOLUCION = isset($ROWmeasignado2["OTROS_4_FECHA_DE_DEVOLUCION"])?$ROWmeasignado2["OTROS_4_FECHA_DE_DEVOLUCION"]:"";
$OTROS_4_OBSERVACIONES = isset($ROWmeasignado2["OTROS_4_OBSERVACIONES"])?$ROWmeasignado2["OTROS_4_OBSERVACIONES"]:"";
$CMEASIGNADO2 = isset($ROWmeasignado2["CMEASIGNADO2"])?$ROWmeasignado2["CMEASIGNADO2"]:"";



$ROWmeasignado3 = $conexion->variablesMEASIGNADO3();

$ROW2= array( );
//print_r($ROW);
$ROWfmeasignado3a1 = $conexion->contadorporcentaje($ROWmeasignado3,$ROW2);
$A_TALLA = isset($ROWmeasignado3["A_TALLA"])?$ROWmeasignado3["A_TALLA"]:"";
$A_FECHA_DE_ENTREGA = isset($ROWmeasignado3["A_FECHA_DE_ENTREGA"])?$ROWmeasignado3["A_FECHA_DE_ENTREGA"]:"";
$A_FECHA_DE_DEVOLUCION = isset($ROWmeasignado3["A_FECHA_DE_DEVOLUCION"])?$ROWmeasignado3["A_FECHA_DE_DEVOLUCION"]:"";
$A_OBSERVACIONES = isset($ROWmeasignado3["A_OBSERVACIONES"])?$ROWmeasignado3["A_OBSERVACIONES"]:"";
$B_TALLA = isset($ROWmeasignado3["B_TALLA"])?$ROWmeasignado3["B_TALLA"]:"";
$B_FECHA_DE_ENTREGA = isset($ROWmeasignado3["B_FECHA_DE_ENTREGA"])?$ROWmeasignado3["B_FECHA_DE_ENTREGA"]:"";
$B_FECHA_DE_DEVOLUCION = isset($ROWmeasignado3["B_FECHA_DE_DEVOLUCION"])?$ROWmeasignado3["B_FECHA_DE_DEVOLUCION"]:"";
$DANIEL_OBSERVACIONES = isset($ROWmeasignado3["DANIEL_OBSERVACIONES"])?$ROWmeasignado3["DANIEL_OBSERVACIONES"]:"";
$DANIEL_TALLA = isset($ROWmeasignado3["DANIEL_TALLA"])?$ROWmeasignado3["DANIEL_TALLA"]:"";
$C_FECHA_DE_ENTREGA = isset($ROWmeasignado3["C_FECHA_DE_ENTREGA"])?$ROWmeasignado3["C_FECHA_DE_ENTREGA"]:"";
$C_FECHA_DE_DEVOLUCION = isset($ROWmeasignado3["C_FECHA_DE_DEVOLUCION"])?$ROWmeasignado3["C_FECHA_DE_DEVOLUCION"]:"";
$C_OBSERVACIONES = isset($ROWmeasignado3["C_OBSERVACIONES"])?$ROWmeasignado3["C_OBSERVACIONES"]:"";
$D_TALLA = isset($ROWmeasignado3["D_TALLA"])?$ROWmeasignado3["D_TALLA"]:"";
$D_FECHA_DE_ENTREGA = isset($ROWmeasignado3["D_FECHA_DE_ENTREGA"])?$ROWmeasignado3["D_FECHA_DE_ENTREGA"]:"";
$D_FECHA_DE_DEVOLUCION = isset($ROWmeasignado3["D_FECHA_DE_DEVOLUCION"])?$ROWmeasignado3["D_FECHA_DE_DEVOLUCION"]:"";
$D_OBSERVACIONES = isset($ROWmeasignado3["D_OBSERVACIONES"])?$ROWmeasignado3["D_OBSERVACIONES"]:"";
$E_TALLA = isset($ROWmeasignado3["E_TALLA"])?$ROWmeasignado3["E_TALLA"]:"";
$E_FECHA_DE_ENTREGA = isset($ROWmeasignado3["E_FECHA_DE_ENTREGA"])?$ROWmeasignado3["E_FECHA_DE_ENTREGA"]:"";
$E_FECHA_DE_DEVOLUCION = isset($ROWmeasignado3["E_FECHA_DE_DEVOLUCION"])?$ROWmeasignado3["E_FECHA_DE_DEVOLUCION"]:"";
$E_OBSERVACIONES = isset($ROWmeasignado3["E_OBSERVACIONES"])?$ROWmeasignado3["E_OBSERVACIONES"]:"";
$F_TALLA = isset($ROWmeasignado3["F_TALLA"])?$ROWmeasignado3["F_TALLA"]:"";
$F_FECHA_DE_ENTREGA = isset($ROWmeasignado3["F_FECHA_DE_ENTREGA"])?$ROWmeasignado3["F_FECHA_DE_ENTREGA"]:"";
$F_FECHA_DE_DEVOLUCION = isset($ROWmeasignado3["F_FECHA_DE_DEVOLUCION"])?$ROWmeasignado3["F_FECHA_DE_DEVOLUCION"]:"";
$F_OBSERVACIONES = isset($ROWmeasignado3["F_OBSERVACIONES"])?$ROWmeasignado3["F_OBSERVACIONES"]:"";
$G_TALLA = isset($ROWmeasignado3["G_TALLA"])?$ROWmeasignado3["G_TALLA"]:"";
$G_FECHA_DE_ENTREGA = isset($ROWmeasignado3["G_FECHA_DE_ENTREGA"])?$ROWmeasignado3["G_FECHA_DE_ENTREGA"]:"";
$G_FECHA_DE_DEVOLUCION = isset($ROWmeasignado3["G_FECHA_DE_DEVOLUCION"])?$ROWmeasignado3["G_FECHA_DE_DEVOLUCION"]:"";
$G_OBSERVACIONES = isset($ROWmeasignado3["G_OBSERVACIONES"])?$ROWmeasignado3["G_OBSERVACIONES"]:"";
$CMEASIGNADO3 = isset($ROWmeasignado3["CMEASIGNADO3"])?$ROWmeasignado3["CMEASIGNADO3"]:""; 







